import { tasksForProject } from '../queueStorage'
import type { InitializerStepResult } from './initializerTypes'

/**
 * The Development Queue starts empty by design — future work is
 * generated by Engineering Intelligence, the Engineering Director, and
 * the Planning Engine, never by the Initializer (that would be exactly
 * the "generated tasks" the spec forbids). queueStorage already returns
 * [] for a project with no tasks, so there is nothing to create; this
 * step exists only to confirm that and make the queue's readiness
 * explicit in the audit trail.
 */
export function initializeQueue(projectSlug: string): InitializerStepResult {
  const existing = tasksForProject(projectSlug)
  return {
    step: 'Development Queue',
    created: [],
    skipped: existing.length > 0 ? [`${existing.length} existing task(s) left untouched`] : ['Queue confirmed empty'],
  }
}
