// Errors
export { RuntimeError } from './errors'
export type { VaiosError, VaiosErrorCode, VaiosErrorDomain } from '@/lib/ai-framework/errors/taxonomy'

// Dependency Injection
export { DIContainer } from './di'
export type { ServiceFactory, ServiceLifetime, DIServiceRegistrationInfo } from './di'

// Registries
export { ServiceRegistry, ComponentRegistry, ProviderRegistry, SkillRegistry } from './registries'
export type {
	ServiceRegistration,
	ComponentRegistration,
	ServiceBatchRegistrationResult,
	RegistryHealthSummary,
} from './registries'

// Provider abstraction
export type {
	ProviderType,
	ProviderAvailabilityStatus,
	ProviderCapabilityMetadata,
	ProviderVersionMetadata,
	ProviderHealthSnapshot,
	ProviderContractMetadata,
	AIProviderRequest,
	AIProviderResponse,
	ChatProviderRequest,
	ChatProviderResponse,
	EmbeddingProviderRequest,
	EmbeddingProviderResponse,
	ImageProviderRequest,
	ImageProviderResponse,
	SpeechProviderRequest,
	SpeechProviderResponse,
	ModerationProviderRequest,
	ModerationProviderResponse,
	BaseProviderContract,
	AIProvider,
	ChatProvider,
	EmbeddingProvider,
	ImageProvider,
	SpeechProvider,
	ModerationProvider,
	ProviderRegistration,
} from './providers'

// Skills foundation
export type {
	SkillCategory,
	SkillCapabilityDeclaration,
	SkillMetadata,
	SkillContract,
	SkillRegistration,
} from './skills'

// Runtime registration validation
export {
	RegistrationValidationService,
	ServiceRegistrationValidator,
	ProviderRegistrationValidator,
	ProviderAdapterValidator,
	SkillRegistrationValidator,
	MemoryRegistrationValidator,
	KnowledgeRegistrationValidator,
	ReasoningPipelineValidator,
	WorkflowValidator,
	AITeamValidator,
	PromptConstructionValidator,
	ExecutionOrchestratorValidator,
	ExecutionGatewayValidator,
	KnowledgeAssemblyValidator,
	RetrievalStrategyPlanningValidator,
	KnowledgeResolutionValidator,
	KnowledgeSelectionValidator,
	KnowledgeQualityValidator,
	KnowledgeReadinessValidator,
	KnowledgeCertificationValidator,
	ReasoningEngineValidator,
	StrategicReasoningValidator,
	TacticalPlanningValidator,
	DecisionIntelligenceValidator,
	ActionIntelligenceValidator,
	AutonomousWorkflowValidator,
	AutonomousTaskValidator,
	AutonomousAgentValidator,
	AutonomousProjectValidator,
	AutonomousWorkspaceValidator,
	AutonomousRecoveryValidator,
	DesktopIntegrationValidator,
	IDEIntegrationValidator,
	TerminalIntegrationValidator,
	BrowserIntegrationValidator,
	GitIntegrationValidator,
	SourceControlValidator,
	RepositoryIntelligenceValidator,
	ExecutionReadinessValidator,
} from './validation'
export type {
	RegistrationScope,
	RegistrationDiagnostic,
	RegistrationValidationResult,
	ServiceRegistrationInput,
	ProviderRegistrationInput,
	SkillRegistrationInput,
	MemoryClassification,
	MemoryLifecycleState,
	MemoryGovernanceInput,
	MemoryMetadataInput,
	MemoryRegistrationInput,
	KnowledgeDomain,
	KnowledgeRelationshipType,
	KnowledgeLifecycleStatus,
	KnowledgeGovernanceInput,
	KnowledgeReferenceInput,
	KnowledgeRelationshipInput,
	KnowledgeMetadataInput,
	KnowledgeRegistrationInput,
	ReasoningPipelineStage,
	ReasoningPipelineStatus,
	ReasoningArtifactType,
	ReasoningGovernanceInput,
	ReasoningMetadataInput,
	ReasoningRegistrationInput,
	ReasoningStageRegistrationInput,
	ReasoningArtifactInput,
	ReasoningEngineStage,
	ReasoningEngineGovernanceInput,
	ReasoningEngineRegistrationInput,
	ReasoningEngineSessionInput,
	ReasoningEngineContextInput,
	ReasoningObjectiveInput,
	ReasoningConstraintInput,
	ReasoningAssumptionInput,
	ReasoningEvidenceInput,
	ReasoningDecisionPointInput,
	ReasoningOutcomeInput,
	ReasoningSummaryInput,
	ReasoningPlanInput,
	ReasoningOutputInput,
	StrategicThinkingStage,
	StrategicGovernanceInput,
	StrategicReasoningRegistrationInput,
	StrategicReasoningSessionInput,
	StrategicReasoningContextInput,
	StrategicObjectiveInput,
	StrategicProblemInput,
	StrategicConstraintInput,
	StrategicAssumptionInput,
	StrategicOpportunityInput,
	StrategicRiskInput,
	StrategicScenarioInput,
	StrategicOutcomeInput,
	StrategicRecommendationInput,
	StrategicPlanningInput,
	TacticalPlanningStage,
	TacticalGovernanceInput,
	TacticalPlanningRegistrationInput,
	TacticalPlanningSessionInput,
	TacticalPlanningContextInput,
	TacticalObjectiveInput,
	TacticalTaskInput,
	TacticalMilestoneInput,
	TacticalDependencyInput,
	TacticalConstraintInput,
	TacticalResourceInput,
	TacticalScheduleInput,
	TacticalOutcomeInput,
	TacticalRecommendationInput,
	TacticalPlanInput,
	DecisionLifecycleStage,
	DecisionGovernanceInput,
	DecisionIntelligenceRegistrationInput,
	DecisionIntelligenceSessionInput,
	DecisionIntelligenceContextInput,
	DecisionCandidateInput,
	DecisionOptionInput,
	DecisionConstraintInput,
	DecisionRiskInput,
	DecisionTradeoffInput,
	DecisionImpactInput,
	DecisionRecommendationInput,
	DecisionOutcomeInput,
	DecisionSummaryInput,
	DecisionLifecycleStateInput,
	DecisionPackageInput,
	ActionLifecycleStage,
	ActionGovernanceInput,
	ActionIntelligenceRegistrationInput,
	ActionIntelligenceSessionInput,
	ActionIntelligenceContextInput,
	ActionPriorityInput,
	ActionGroupInput,
	ActionItemInput,
	ActionDependencyInput,
	ActionConstraintInput,
	ActionAssignmentInput,
	ActionMilestoneInput,
	ActionOutcomeInput,
	ActionSummaryInput,
	ActionLifecycleStateInput,
	ActionPlanInput,
	ActionReadinessInput,
	AutonomousWorkflowLifecycleStage,
	AutonomousWorkflowGovernanceInput,
	AutonomousWorkflowRegistrationInput,
	AutonomousWorkflowSessionInput,
	AutonomousWorkflowContextInput,
	AutonomousWorkflowObjectiveInput,
	AutonomousWorkflowPhaseInput,
	AutonomousWorkflowStepInput,
	AutonomousWorkflowDependencyInput,
	AutonomousWorkflowConstraintInput,
	AutonomousWorkflowCheckpointInput,
	AutonomousWorkflowApprovalInput,
	AutonomousWorkflowOutcomeInput,
	AutonomousWorkflowSummaryInput,
	AutonomousWorkflowLifecycleStateInput,
	AutonomousWorkflowInput,
	AutonomousWorkflowReadinessInput,
	AutonomousTaskLifecycleStage,
	AutonomousTaskGovernanceInput,
	AutonomousTaskRegistrationInput,
	AutonomousTaskSessionInput,
	AutonomousTaskContextInput,
	AutonomousTaskObjectiveInput,
	AutonomousTaskGroupInput,
	AutonomousTaskTaskInput,
	AutonomousTaskDependencyInput,
	AutonomousTaskConstraintInput,
	AutonomousTaskCheckpointInput,
	AutonomousTaskAssignmentInput,
	AutonomousTaskApprovalInput,
	AutonomousTaskOutcomeInput,
	AutonomousTaskSummaryInput,
	AutonomousTaskLifecycleStateInput,
	AutonomousTaskInput,
	AutonomousTaskReadinessInput,
	AutonomousAgentLifecycleStage,
	AutonomousAgentGovernanceInput,
	AutonomousAgentRegistrationInput,
	AutonomousAgentSessionInput,
	AutonomousAgentContextInput,
	AutonomousAgentRoleInput,
	AutonomousAgentCapabilityInput,
	AgentAssignmentInput,
	AutonomousAgentResponsibilityInput,
	AutonomousAgentDependencyInput,
	AutonomousAgentCommunicationInput,
	AutonomousAgentDecisionInput,
	AutonomousAgentOutcomeInput,
	AutonomousAgentSummaryInput,
	AutonomousAgentInput,
	AutonomousAgentLifecycleStateInput,
	CoordinationGroupInput,
	CoordinationQueueInput,
	CoordinationCheckpointInput,
	CoordinationDependencyInput,
	CoordinationConflictInput,
	CoordinationResolutionInput,
	CoordinationAuditInput,
	CoordinationPlanInput,
	AutonomousProjectLifecycleStage,
	AutonomousProjectGovernanceInput,
	AutonomousProjectRegistrationInput,
	AutonomousProjectSessionInput,
	AutonomousProjectContextInput,
	ProjectPortfolioInput,
	ProjectMilestoneInput,
	ProjectDependencyInput,
	ProjectConstraintInput,
	ProjectResourceInput,
	ProjectRiskInput,
	ProjectDecisionInput,
	ProjectOutcomeInput,
	AutonomousProjectSummaryInput,
	AutonomousProjectLifecycleStateInput,
	AutonomousProjectInput,
	ProjectCoordinationInput,
	AutonomousWorkspaceLifecycleStage,
	AutonomousWorkspaceGovernanceInput,
	AutonomousWorkspaceRegistrationInput,
	AutonomousWorkspaceSessionInput,
	AutonomousWorkspaceContextInput,
	WorkspaceProfileInput,
	WorkspaceEnvironmentInput,
	WorkspaceLayoutInput,
	IDEInstanceInput,
	TerminalInstanceInput,
	BrowserInstanceInput,
	ApplicationInstanceInput,
	WindowInstanceInput,
	WorkspaceProcessInput,
	WorkspaceServiceInput,
	WorkspaceConnectionInput,
	WorkspaceDependencyInput,
	WorkspaceCheckpointInput,
	WorkspaceResourceInput,
	WorkspaceResourceModelInput,
	WorkspaceStateInput,
	WorkspaceOutcomeInput,
	WorkspaceSummaryInput,
	WorkspaceSessionInput,
	AutonomousWorkspaceLifecycleStateInput,
	WorkspaceConfigurationInput,
	WorkspaceSnapshotInput,
	AutonomousRecoveryLifecycleStage,
	AutonomousRecoveryGovernanceInput,
	AutonomousRecoveryRegistrationInput,
	AutonomousRecoverySessionInput,
	AutonomousRecoveryContextInput,
	RecoveryStateInput,
	RecoveryDependencyInput,
	RecoveryStrategyInput,
	RecoveryCheckpointInput,
	RecoveryTimelineInput,
	RecoveryRecommendationInput,
	RecoveryOutcomeInput,
	RecoverySummaryInput,
	SessionSnapshotInput,
	SessionRestorePointInput,
	WorkspaceRestorePlanInput,
	RuntimeRestorePlanInput,
	ServiceRestorePlanInput,
	ExecutionResumePlanInput,
	ContinuityAuditInput,
	SessionContinuityPlanInput,
	RecoveryPlanInput,
	AutonomousRecoveryLifecycleStateInput,
	RecoverySnapshotInput,
	DesktopIntegrationGovernanceInput,
	DesktopIntegrationRegistrationInput,
	DesktopIntegrationSessionInput,
	DesktopIntegrationContextInput,
	DesktopProfileInput,
	DesktopEnvironmentInput,
	DesktopApplicationInput,
	DesktopWorkspaceInput,
	DesktopWindowInput,
	DesktopIntegrationStateInput,
	DesktopSessionInput,
	DesktopProcessInput,
	DesktopCapabilityInput,
	DesktopSummaryInput,
	IDETargetInput,
	BrowserTargetInput,
	TerminalTargetInput,
	ApplicationTargetInput,
	ServiceTargetInput,
	ProcessTargetInput,
	WorkspaceTargetInput,
	WindowTargetInput,
	AutomationTargetInput,
	IntegrationDependencyInput,
	IntegrationTargetInput,
	DesktopConfigurationInput,
	DesktopIntegrationLifecycleStage,
	DesktopIntegrationLifecycleStateInput,
	IDEIntegrationGovernanceInput,
	IDEIntegrationRegistrationInput,
	IDEIntegrationSessionInput,
	IDEIntegrationContextInput,
	IDEProfileInput,
	IDEWorkspaceInput,
	IDEProjectInput,
	IDEWindowInput,
	IDEEditorInput,
	IDETerminalInput,
	IDEExtensionInput,
	IDECapabilityInput,
	IDESummaryInput,
	WorkspaceFolderInput,
	OpenFileInput,
	EditorGroupInput,
	CursorPositionInput,
	BreakpointInput,
	TerminalSessionInput,
	DebugSessionInput,
	TaskRunnerInput,
	IDEProcessInput,
	IDECheckpointInput,
	IDEResourceInput,
	IDEStateInput,
	IDEConfigurationInput,
	IDELifecycleStateInput,
	IDEIntegrationLifecycleStage,
	TerminalIntegrationGovernanceInput,
	TerminalIntegrationRegistrationInput,
	TerminalIntegrationSessionInput,
	TerminalIntegrationContextInput,
	TerminalProfileInput,
	TerminalEnvironmentInput,
	TerminalStateInput,
	TerminalWorkspaceInput,
	TerminalWindowInput,
	TerminalInstanceInput as TerminalIntegrationInstanceInput,
	TerminalCapabilityInput,
	TerminalShellInput,
	TerminalCommandInput,
	TerminalSummaryInput,
	ShellSessionInput,
	ShellProfileInput,
	CommandQueueInput,
	CommandHistoryInput,
	WorkingDirectoryInput,
	EnvironmentVariableInput,
	ProcessHandleInput,
	ConsoleBufferInput,
	TerminalCheckpointInput,
	TerminalSnapshotInput,
	TerminalResourceInput,
	TerminalConfigurationInput,
	TerminalLifecycleStateInput,
	TerminalIntegrationLifecycleStage,
	BrowserIntegrationGovernanceInput,
	BrowserIntegrationRegistrationInput,
	BrowserIntegrationSessionInput,
	BrowserIntegrationContextInput,
	BrowserProfileInput,
	BrowserEnvironmentInput,
	BrowserStateInput,
	BrowserWindowInput,
	BrowserSessionInput,
	BrowserTabInput,
	BrowserCapabilityInput,
	BrowserExtensionInput,
	BrowserBookmarkInput,
	BrowserSummaryInput,
	WebPageInput,
	URLReferenceInput,
	NavigationHistoryInput,
	CookieStoreInput,
	LocalStorageReferenceInput,
	SessionStorageReferenceInput,
	BrowserDeveloperToolsInput,
	BrowserNetworkSessionInput,
	BrowserCheckpointInput,
	BrowserSnapshotInput,
	BrowserResourceInput,
	BrowserConfigurationInput,
	BrowserLifecycleStateInput,
	BrowserIntegrationLifecycleStage,
	GitIntegrationGovernanceInput,
	GitIntegrationRegistrationInput,
	GitIntegrationSessionInput,
	GitIntegrationContextInput,
	GitStateInput,
	GitRepositoryInput,
	GitBranchInput,
	GitCommitInput,
	GitTagInput,
	GitRemoteInput,
	GitWorkspaceInput,
	GitCapabilityInput,
	GitIdentityInput,
	GitSummaryInput,
	StagingAreaInput,
	CommitHistoryInput,
	BranchGraphInput,
	MergeRequestInput,
	MergeConflictInput,
	RepositorySnapshotInput,
	FileChangeInput,
	WorkingTreeInput,
	GitCheckpointInput,
	RepositoryStateInput,
	GitResourceInput,
	GitConfigurationInput,
	GitLifecycleStateInput,
	GitIntegrationLifecycleStage,
	SourceControlLifecycleStage,
	SourceControlGovernanceInput,
	SourceControlRegistrationInput,
	SourceControlSessionInput,
	SourceControlContextInput,
	SourceControlStateInput,
	RepositoryWorkspaceInput,
	RepositoryGroupInput,
	BranchStrategyInput,
	CommitStrategyInput,
	MergeStrategyInput,
	ReleaseStrategyInput,
	RepositoryPolicyInput,
	RepositoryGovernanceInput,
	SourceControlCapabilityInput,
	SourceControlSummaryInput,
	RepositoryPlanInput,
	BranchPlanInput,
	CommitPlanInput,
	MergePlanInput,
	ReleasePlanInput,
	SynchronizationPlanInput,
	ConflictResolutionPlanInput,
	RepositoryCheckpointInput,
	RepositoryAuditInput,
	SourceControlResourceInput,
	SourceControlConfigurationInput,
	SourceControlLifecycleStateInput,
	RepositoryIntelligenceLifecycleStage,
	RepositoryIntelligenceGovernanceInput,
	RepositoryIntelligenceRegistrationInput,
	RepositoryIntelligenceSessionInput,
	RepositoryIntelligenceContextInput,
	RepositoryIntelligenceStateInput,
	RepositoryProfileInput,
	RepositoryTopologyInput,
	RepositoryMetricsInput,
	RepositoryHealthInput,
	RepositoryQualityInput,
	RepositoryDependencyGraphInput,
	RepositoryKnowledgeMapInput,
	RepositoryRiskProfileInput,
	RepositoryEvolutionInput,
	RepositoryIntelligenceSummaryInput,
	RepositoryAnalysisPlanInput,
	ArchitectureAnalysisInput,
	DependencyAnalysisInput,
	QualityAnalysisInput,
	ComplexityAnalysisInput,
	TechnicalDebtAnalysisInput,
	ChangeAnalysisInput,
	RepositoryInsightInput,
	RepositoryRecommendationInput,
	RepositoryIntelligenceAuditInput,
	RepositoryIntelligenceResourceInput,
	RepositoryIntelligenceConfigurationInput,
	RepositoryIntelligenceLifecycleStateInput,
	ExecutionReadinessGovernanceInput,
	ExecutionReadinessRegistrationInput,
	ExecutionReadinessSessionInput,
	ExecutionReadinessContextInput,
	ExecutionReadinessStatusInput,
	ExecutionReadinessDecisionInput,
	ExecutionReadinessCriteriaInput,
	ExecutionReadinessRecommendationInput,
	ExecutionReadinessEvidenceInput,
	ExecutionReadinessTraceabilityInput,
	ExecutionReadinessSummaryInput,
	ExecutionReadinessReportInput,
	ExecutableActionPackageInput,
	ExecutableWorkflowPackageInput,
	ExecutableContextPackageInput,
	ExecutableConstraintPackageInput,
	ExecutableValidationPackageInput,
	ExecutionApprovalPackageInput,
	ExecutionAuditPackageInput,
	ActionCompletionPolicyInput,
	DependencyCompletionPolicyInput,
	ValidationCompletionPolicyInput,
	ApprovalCompletionPolicyInput,
	WorkflowReadinessPolicyInput,
	ExecutionSafetyPolicyInput,
	ExecutionReadinessPolicyInput,
	ExecutionApprovalInput,
	ExecutionPackageInput,
	ProviderRuntimeLifecycleState,
	ProviderConfigurationInput,
	AdapterLifecycleState,
	ProviderAdapterCapabilityInput,
	ProviderAdapterRegistrationInput,
	ProviderAdapterConfigurationInput,
	AISpecialistRole,
	AITeamGovernanceInput,
	AISpecialistRegistrationInput,
	AITeamRegistrationInput,
	AITeamAssignmentInput,
	PromptClassification,
	PromptGovernanceInput,
	PromptMetadataInput,
	PromptRegistrationInput,
	PromptTemplateRegistrationInput,
	PromptContextSectionInput,
	PromptContextPackageInput,
	PromptPackageInput,
	ExecutionPipelineState,
	ExecutionGovernanceInput,
	ExecutionStageInput,
	ExecutionWorkPackageInput,
	ExecutionContextInput,
	ExecutionPlanInput,
	ExecutionRegistrationInput,
	ExecutionResponseStatus,
	ExecutionGatewayRequestInput,
	ExecutionDispatchInput,
	ProviderResolutionInput,
	ExecutionGatewayResponseInput,
	ExecutionAuditRecordInput,
	RetrievalPriority,
	RetrievalScope,
	RetrievalStrategy,
	KnowledgeSourceType,
	RetrievalSourceDescriptorInput,
	RetrievalRequestInput,
	RetrievalPlanInput,
	KnowledgeReferenceAssemblyInput,
	KnowledgePackageInput,
	KnowledgePrioritisationInput,
	KnowledgeAssemblyRegistrationInput,
	QueryIntent,
	QueryScope,
	QueryPriority,
	RetrievalStrategyPattern,
	SourcePlanningTarget,
	StrategyGovernanceInput,
	QueryPlanInput,
	QueryPlanningRegistrationInput,
	SourcePlanningInput,
	RetrievalStrategyDefinitionInput,
	RetrievalPackageInput,
	ContextCompositionSource,
	ContextSectionType,
	ContextOrderingMode,
	ContextPrioritisationMode,
	ContextCompletenessStatus,
	ContextGapSeverity,
	MergePolicyStrategy,
	ConflictResolutionStrategy,
	MissingKnowledgeStrategy,
	ContextGovernanceInput,
	ResolutionContextReferenceInput,
	ContextCompositionInput,
	ResolutionPolicyInput,
	KnowledgeResolutionRegistrationInput,
	KnowledgeResolutionSessionInput,
	CandidateKnowledgeSource,
	SelectionPriority,
	SelectionDecisionType,
	RelevancePolicyStrategy,
	ConflictPolicyStrategy,
	SelectionGovernanceInput,
	EvidenceReferenceInput,
	EvidencePackageInput,
	SelectionPolicyInput,
	KnowledgeSelectionRegistrationInput,
	KnowledgeSelectionSessionInput,
	KnowledgeSelectionInput,
	KnowledgeSelectionContextInput,
	QualityAssessmentStatus,
	ConflictSeverity,
	ConflictCategory,
	GapSeverity,
	QualityGovernanceInput,
	KnowledgeQualityRegistrationInput,
	KnowledgeQualitySessionInput,
	KnowledgeQualityContextInput,
	KnowledgeQualityReportInput,
	ConflictAnalysisInput,
	GapAnalysisInput,
	KnowledgeQualityPolicyInput,
	ConflictReferenceInput,
	QualityConflictPolicyStrategy,
	ReadinessStatus,
	ReadinessDecision,
	ReadinessGovernanceInput,
	ReadinessPolicyInput,
	KnowledgeReadinessRegistrationInput,
	KnowledgeReadinessSessionInput,
	KnowledgeReadinessContextInput,
	ReadinessReportInput,
	PromptHandoffPackageInput,
	CertificationStatus,
	CertificationDecision,
	CertificationGovernanceInput,
	CertificationPolicyInput,
	KnowledgeCertificationRegistrationInput,
	KnowledgeCertificationSessionInput,
	KnowledgeCertificationContextInput,
	CertificationCriteriaInput,
	CertificationRecommendationInput,
	CertificationEvidenceInput,
	CertificationTraceabilityInput,
	KnowledgeCertificationReportInput,
	PromptDeliveryPackageInput,
	WorkflowState,
	WorkflowArtifactType,
	WorkflowGovernanceInput,
	WorkflowStepInput,
	WorkflowMetadataInput,
	WorkflowRegistrationInput,
	WorkflowArtifactInput,
} from './validation'
export { PROVIDER_RUNTIME_LIFECYCLE_STATES } from './validation'
export { ADAPTER_LIFECYCLE_STATES } from './validation'
export { AI_SPECIALIST_ROLES } from './validation'
export { PROMPT_CLASSIFICATIONS } from './validation'
export { EXECUTION_PIPELINE_STATES } from './validation'
export { EXECUTION_RESPONSE_STATUSES } from './validation'
export { RETRIEVAL_PRIORITIES } from './validation'
export { RETRIEVAL_SCOPES } from './validation'
export { RETRIEVAL_STRATEGIES } from './validation'
export { KNOWLEDGE_SOURCE_TYPES } from './validation'
export { QUERY_INTENTS } from './validation'
export { QUERY_SCOPES } from './validation'
export { QUERY_PRIORITIES } from './validation'
export { RETRIEVAL_STRATEGY_PATTERNS } from './validation'
export { SOURCE_PLANNING_TARGETS } from './validation'
export { CONTEXT_COMPOSITION_SOURCES } from './validation'
export { CONTEXT_SECTION_TYPES } from './validation'
export { CONTEXT_ORDERING_MODES } from './validation'
export { CONTEXT_PRIORITISATION_MODES } from './validation'
export { CONTEXT_COMPLETENESS_STATUSES } from './validation'
export { CONTEXT_GAP_SEVERITIES } from './validation'
export { MERGE_POLICY_STRATEGIES } from './validation'
export { CONFLICT_RESOLUTION_STRATEGIES } from './validation'
export { MISSING_KNOWLEDGE_STRATEGIES } from './validation'
export { CANDIDATE_KNOWLEDGE_SOURCES } from './validation'
export { SELECTION_PRIORITIES } from './validation'
export { SELECTION_DECISION_TYPES } from './validation'
export { RELEVANCE_POLICY_STRATEGIES } from './validation'
export { CONFLICT_POLICY_STRATEGIES } from './validation'
export { QUALITY_ASSESSMENT_STATUSES } from './validation'
export { CONFLICT_SEVERITIES } from './validation'
export { CONFLICT_CATEGORIES } from './validation'
export { GAP_SEVERITIES } from './validation'
export { QUALITY_CONFLICT_POLICY_STRATEGIES } from './validation'
export { READINESS_STATUSES } from './validation'
export { READINESS_DECISIONS } from './validation'
export { CERTIFICATION_STATUSES } from './validation'
export { CERTIFICATION_DECISIONS } from './validation'
export { REASONING_ENGINE_STAGES } from './validation'
export { STRATEGIC_THINKING_STAGES } from './validation'
export { TACTICAL_PLANNING_STAGES } from './validation'
export { DECISION_LIFECYCLE_STAGES } from './validation'
export { ACTION_LIFECYCLE_STAGES } from './validation'

// Provider runtime foundation
export {
	ProviderManager,
	ProviderFactory,
	ProviderResolver,
	ProviderSelectionEngine,
	ProviderCapabilityResolver,
	ProviderHealthMonitor,
	ProviderConfigurationManager,
} from './providerRuntime'
export type {
	ProviderRuntimeConfiguration,
	ProviderSelectionRequest,
	ProviderSelectionResult,
	ProviderRuntimeDescriptor,
	ProviderAvailabilityHealth,
	ProviderConfigurationHealth,
	ProviderLifecycleHealth,
	ProviderRuntimeHealth,
	ChatCompletionRuntime,
	EmbeddingsRuntime,
	ImageGenerationRuntime,
	SpeechRuntime,
	ModerationRuntime,
} from './providerRuntime'

// Provider adapter framework
export {
	ProviderAdapterManager,
	ProviderAdapterRegistry,
	ProviderAdapterFactory,
	ProviderAdapterResolver,
} from './providerAdapter'
export type {
	ProviderAdapterType,
	ProviderAdapterMetadata,
	ProviderAdapterDiagnostics,
	ProviderAdapterRegistration,
	ProviderAdapterConfiguration,
	ProviderAdapterRuntimeDescriptor,
	ProviderAdapterRegistryHealth,
	ProviderAdapterConfigurationHealth,
	ProviderAdapterLifecycleHealth,
	ProviderAdapterValidationHealth,
	ProviderAdapterFrameworkHealth,
	ChatProviderAdapter,
	EmbeddingProviderAdapter,
	ImageProviderAdapter,
	SpeechProviderAdapter,
	ModerationProviderAdapter,
	ProviderAdapterContract,
} from './providerAdapter'

// AI Team orchestrator foundation
export {
	AITeamManager,
	AITeamRegistry,
	AISpecialistRegistry,
} from './aiTeam'
export type {
	AISpecialist,
	AITeamGovernance,
	AITeamMetadata,
	AITeamContext,
	AITeamSession,
	AITeamDiagnostic,
	AITeamRegistration,
	TeamWorkItem,
	TeamAssignment,
	ResponsibilityMapping,
	RoleAssignment,
	TeamComposition,
	AITeamHealth,
} from './aiTeam'

// Prompt construction foundation
export {
	PromptConstructionManager,
	PromptRegistry,
	PromptTemplateRegistry,
} from './promptConstruction'
export type {
	PromptOwnership,
	PromptGovernance,
	PromptMetadata,
	PromptContextSection,
	RuntimeContextSourceModel,
	MemoryContextSourceModel,
	BusinessBrainContextSourceModel,
	WorkflowContextSourceModel,
	ReasoningContextSourceModel,
	AITeamContextSourceModel,
	ProviderContextSourceModel,
	UserContextSourceModel,
	TenantContextSourceModel,
	PromptContext,
	PromptPackage,
	PromptDiagnostics,
	PromptTemplate,
	PromptRegistration,
	PromptAssemblyPipeline,
	PromptConstructionHealth,
} from './promptConstruction'

// Execution orchestrator foundation
export {
	ExecutionRegistry,
	ExecutionOrchestrator,
} from './executionOrchestrator'
export type {
	ExecutionPipelineState as RuntimeExecutionPipelineState,
	ExecutionGovernance,
	ExecutionStage,
	ExecutionWorkPackage,
	ExecutionContext,
	ExecutionPlan,
	ExecutionSession,
	ExecutionMetadata,
	ExecutionDiagnostics,
	ExecutionRegistration,
	RuntimeCoordinationContract,
	ExecutionOrchestratorHealth,
} from './executionOrchestrator'

// Execution gateway foundation
export {
	ExecutionGateway,
	ExecutionDispatcher,
	ExecutionRequestRouter,
	ExecutionResponseRouter,
	ExecutionSessionManager,
	ExecutionAuditManager,
} from './executionGateway'
export type {
	ExecutionRequestIdentity,
	ExecutionRequestMetadata,
	ExecutionRequestContext,
	ExecutionPromptPackage,
	ExecutionProviderSelection,
	ExecutionAdapterSelection,
	ExecutionConstraints,
	ExecutionTimeoutPolicy,
	ExecutionRetryPolicy,
	ExecutionExpectedOutput,
	ExecutionGatewayRequest,
	ProviderResolutionRecord,
	DispatchRoute,
	RetryPlan,
	ExecutionDispatchRecord,
	ExecutionResponseMetadata,
	ExecutionProviderMetadata,
	ExecutionCostMetadata,
	ExecutionTimingMetadata,
	ExecutionAuditReference,
	ExecutionDiagnostics as GatewayExecutionDiagnostics,
	ExecutionGatewayResponse,
	ExecutionAuditRecord,
	ExecutionSession as GatewayExecutionSession,
	ExecutionGatewayHealth,
	ExecutionDispatchHealth,
	ExecutionRoutingHealth,
	ExecutionAuditHealth,
	ExecutionGatewayFrameworkHealth,
} from './executionGateway'

// Knowledge assembly foundation
export {
	KnowledgeAssemblyRegistry,
	KnowledgeAssemblyManager,
} from './knowledgeAssembly'
export type {
	RetrievalSource,
	RetrievalRequest,
	RetrievalPlan,
	RetrievalResultMetadata,
	RetrievedKnowledge,
	SupportingEvidence,
	KnowledgePolicy,
	KnowledgeConstraint,
	HistoricalDecision,
	KnowledgeReference as AssemblyKnowledgeReference,
	ConfidenceSummary,
	KnowledgeGap,
	KnowledgePackage,
	PriorityRules,
	RankingMetadata,
	FreshnessMetadata,
	TrustMetadata,
	SourceWeighting,
	ConflictIndicator,
	CompletenessIndicator,
	KnowledgePrioritisation,
	KnowledgeAssemblyMetadata,
	KnowledgeAssemblyDiagnostics,
	KnowledgeAssemblyContext,
	KnowledgeAssemblySession,
	KnowledgeAssemblyRegistration,
	KnowledgeAssemblyHealth,
} from './knowledgeAssembly'

// Retrieval strategy and query planning foundation
export {
	QueryPlanningRegistry,
	RetrievalStrategyRegistry,
	QueryPlanningManager,
	RetrievalStrategyManager,
} from './retrievalStrategy'
export type {
	RetrievalQuery,
	QueryConstraints,
	QueryExpansion,
	QueryReduction,
	QueryOptimisation,
	QueryMetadata,
	StrategyOwnership,
	StrategyProvenance,
	StrategyGovernance,
	SequentialRetrievalStrategy,
	ParallelRetrievalStrategy,
	ConditionalRetrievalStrategy,
	IncrementalRetrievalStrategy,
	CachedRetrievalStrategy,
	DeferredRetrievalStrategy,
	RetrievalStrategyModel,
	SourcePlanningDescriptor,
	PlannedSource,
	PlannedQuery,
	RetrievalDependency,
	RetrievalOrdering,
	ExpectedEvidence,
	ExpectedKnowledge,
	ExpectedContext,
	RetrievalGap,
	RetrievalRisk,
	RetrievalPackage,
	QueryPlanningMetadata,
	QueryPlanningDiagnostics,
	QueryPlanningContext,
	QueryPlanningRegistration,
	RetrievalStrategyRegistration,
	RetrievalStrategyRuntimeHealth,
} from './retrievalStrategy'

// Knowledge resolution and context composition foundation
export {
	KnowledgeResolutionRegistry,
	KnowledgeResolutionManager,
} from './knowledgeResolution'
export type {
	ContextCompositionSource as RuntimeContextCompositionSource,
	ContextSectionType as RuntimeContextSectionType,
	ContextOrderingMode as RuntimeContextOrderingMode,
	ContextPrioritisationMode as RuntimeContextPrioritisationMode,
	ContextCompletenessStatus as RuntimeContextCompletenessStatus,
	ContextGapSeverity as RuntimeContextGapSeverity,
	KnowledgeResolutionMetadata,
	KnowledgeResolutionDiagnostics,
	KnowledgeResolutionSession,
	KnowledgeResolutionOwnership,
	KnowledgeResolutionProvenance,
	ContextFreshness,
	ContextGovernance,
	MergePolicy,
	ConflictResolutionPolicy,
	SourcePriorityPolicy,
	ContextSizePolicy,
	ContextQualityPolicy,
	MissingKnowledgePolicy,
	ResolutionPolicies,
	ResolvedKnowledge,
	ContextReference,
	ContextDependency,
	ContextGap,
	ContextCompleteness,
	ContextSection,
	ContextOrdering,
	ContextPrioritisation,
	ResolvedContext,
	KnowledgeResolutionContext,
	ContextPackage,
	KnowledgeResolutionRegistration,
	KnowledgeResolutionRuntimeHealth,
} from './knowledgeResolution'

// Knowledge selection and evidence assembly foundation
export {
	KnowledgeSelectionRegistry,
	KnowledgeSelectionManager,
} from './knowledgeSelection'
export type {
	CandidateKnowledgeSource as RuntimeCandidateKnowledgeSource,
	SelectionPriority as RuntimeSelectionPriority,
	SelectionDecisionType as RuntimeSelectionDecisionType,
	KnowledgeSelectionMetadata,
	KnowledgeSelectionDiagnostics,
	KnowledgeSelectionSession,
	SelectionOwnership,
	SelectionProvenance,
	SelectionFreshness,
	SelectionGovernance,
	RelevancePolicy,
	ConfidencePolicy,
	TrustPolicy,
	FreshnessPolicy,
	DiversityPolicy,
	CompletenessPolicy,
	ConflictPolicy,
	EvidenceSufficiencyPolicy,
	SelectionPolicies,
	CandidateKnowledge,
	SelectedKnowledge,
	SelectionCriteria,
	SelectionConstraints,
	SelectionDecision,
	SelectionExclusion,
	SelectionSummary,
	EvidenceSource,
	EvidenceReference,
	EvidenceChainStep,
	EvidenceChain,
	EvidenceSummary,
	EvidenceConfidence,
	EvidenceTraceability,
	EvidenceCoverage,
	EvidencePackage,
	KnowledgeSelectionContext,
	SelectionRecord,
	KnowledgeSelectionRegistration,
	KnowledgeSelectionRuntimeHealth,
} from './knowledgeSelection'

// Knowledge quality and conflict analysis foundation
export {
	KnowledgeQualityRegistry,
	KnowledgeQualityManager,
} from './knowledgeQuality'
export type {
	QualityAssessmentStatus as RuntimeQualityAssessmentStatus,
	ConflictSeverity as RuntimeConflictSeverity,
	ConflictCategory as RuntimeConflictCategory,
	GapSeverity as RuntimeGapSeverity,
	KnowledgeQualityMetadata,
	KnowledgeQualityDiagnostics,
	KnowledgeQualitySession,
	QualityOwnership,
	QualityProvenance,
	QualityFreshness,
	QualityGovernance,
	CompletenessPolicy as QualityCompletenessPolicy,
	ConsistencyPolicy as QualityConsistencyPolicy,
	TrustPolicy as QualityTrustPolicy,
	FreshnessPolicy as QualityFreshnessPolicy,
	ConflictPolicy as QualityConflictPolicy,
	CoveragePolicy as QualityCoveragePolicy,
	RelevancePolicy as QualityRelevancePolicy,
	EvidenceQualityPolicy,
	KnowledgeQualityPolicies,
	CompletenessAssessment,
	FreshnessAssessment,
	TrustAssessment,
	ConfidenceAssessment,
	CoverageAssessment,
	ConsistencyAssessment,
	RelevanceAssessment,
	KnowledgeQualityReport,
	ConflictSource,
	ConflictResolutionRecommendation,
	ConflictTraceability,
	ConflictGroup,
	ConflictDetectionResult,
	ConflictSummary,
	MissingContext,
	MissingEvidence,
	MissingDecision,
	MissingReference,
	GapRecommendation,
	KnowledgeGap as QualityKnowledgeGap,
	GapSummary,
	KnowledgeGapAnalysis,
	KnowledgeQualityContext,
	KnowledgeQualityRegistration,
	KnowledgeQualityRuntimeHealth,
} from './knowledgeQuality'

// Knowledge readiness and prompt handoff foundation
export {
	KnowledgeReadinessRegistry,
	KnowledgeReadinessManager,
} from './knowledgeReadiness'
export type {
	ReadinessStatus as RuntimeReadinessStatus,
	ReadinessDecision as RuntimeReadinessDecision,
	KnowledgeReadinessMetadata,
	KnowledgeReadinessDiagnostics,
	KnowledgeReadinessSession,
	ReadinessOwnership,
	ReadinessProvenance,
	ReadinessFreshness,
	ReadinessGovernance,
	ReadinessCriteria,
	ReadinessScore,
	ReadinessRecommendation,
	ReadinessSummary,
	ReadinessTraceability,
	ReadinessReport,
	FinalContextPackage,
	FinalKnowledgePackage,
	FinalEvidencePackage,
	FinalConstraintPackage,
	FinalObjectivePackage,
	FinalReferencePackage,
	FinalValidationPackage,
	PromptHandoffPackage,
	MinimumCompletenessPolicy,
	MinimumConfidencePolicy,
	MinimumTrustPolicy,
	ConflictTolerancePolicy,
	FreshnessPolicy as ReadinessFreshnessPolicy,
	EvidenceCoveragePolicy,
	PromptReadinessPolicy,
	ReadinessPolicies,
	KnowledgeReadinessContext,
	KnowledgeReadinessRegistration,
	KnowledgeReadinessRuntimeHealth,
} from './knowledgeReadiness'

// Knowledge certification and prompt delivery foundation
export {
	KnowledgeCertificationRegistry,
	KnowledgeCertificationManager,
} from './knowledgeCertification'
export type {
	CertificationStatus as RuntimeCertificationStatus,
	CertificationDecision as RuntimeCertificationDecision,
	KnowledgeCertificationMetadata,
	KnowledgeCertificationDiagnostics,
	KnowledgeCertificationSession,
	CertificationOwnership,
	CertificationProvenance,
	CertificationFreshness,
	CertificationGovernance,
	CertificationCriteria,
	CertificationRecommendation,
	CertificationEvidence,
	CertificationTraceability,
	CertificationSummary,
	KnowledgeCertificationReport,
	CertifiedKnowledgePackage,
	CertifiedEvidencePackage,
	CertifiedContextPackage,
	CertifiedConstraintPackage,
	CertifiedObjectivePackage,
	CertifiedReferencePackage,
	CertifiedValidationPackage,
	PromptDeliveryPackage,
	CompletenessCertificationPolicy,
	ConfidenceCertificationPolicy,
	TrustCertificationPolicy,
	ConflictCertificationPolicy,
	FreshnessCertificationPolicy,
	EvidenceCertificationPolicy,
	PromptDeliveryPolicy,
	CertificationPolicies,
	KnowledgeCertificationContext,
	KnowledgeCertificationRegistration,
	KnowledgeCertificationRuntimeHealth,
} from './knowledgeCertification'

// Memory foundation
export {
	MemoryRegistry,
	MemoryLifecycleManager,
	MemoryManager,
} from './memory'
export type {
	MemoryVisibility,
	MemoryAccessScope,
	MemoryTrustLevel,
	MemoryOwnership,
	MemoryRetentionPolicy,
	MemoryExpirationPolicy,
	MemoryFreshness,
	MemoryGovernance,
	MemoryCapability,
	MemorySession,
	MemoryContext,
	MemoryMetadata,
	MemoryStoreContract,
	MemoryStoreResult,
	MemoryRetrievalContract,
	MemoryRetrievalResult,
	MemoryIndexContract,
	MemoryIndexResult,
	MemoryProvider,
	MemoryRegistration,
	MemoryDraft,
	MemoryLifecycleTransition,
	MemoryLifecycleEvent,
	MemoryLifecycleHealth,
	MemoryValidationHealth,
	MemoryEngineHealth,
} from './memory'

// Business Brain foundation
export {
	KnowledgeDomainRegistry,
	BusinessBrainRegistry,
	KnowledgeLifecycleRegistry,
	BusinessBrainManager,
} from './businessBrain'
export type {
	RuntimeKnowledgeTrustLevel,
	KnowledgeOwnership,
	KnowledgeStewardship,
	RuntimeKnowledgeProvenance,
	KnowledgeFreshness,
	RuntimeKnowledgeGovernance,
	KnowledgeReference,
	KnowledgeRelationship,
	KnowledgeMetadata,
	KnowledgeRegistration,
	KnowledgeDomainDescriptor,
	BusinessKnowledgeModel,
	KnowledgeCatalogEntry,
	KnowledgeCatalog,
	BusinessBrainValidationHealth,
	KnowledgeLifecycleHealth,
	BusinessBrainHealth,
	KnowledgeLookup,
} from './businessBrain'

// Reasoning pipeline foundation
export {
	ReasoningStageRegistry,
	ReasoningRegistry,
	ReasoningPipelineManager,
	ReasoningEngineRegistry,
	ReasoningEngineManager,
} from './reasoning'
export type {
	RuntimeReasoningTrustLevel,
	ReasoningSession,
	ReasoningContext,
	ReasoningRequest,
	ReasoningResult,
	RuntimeReasoningDiagnostic,
	ReasoningArtifact,
	ReasoningMetadata,
	RuntimeReasoningGovernance,
	ReasoningStageDefinition,
	ReasoningRegistration,
	ReasoningPipelineHealth,
	ReasoningEngineMetadata,
	ReasoningEngineDiagnostics,
	ReasoningEngineSession,
	ReasoningEngineOwnership,
	ReasoningEngineProvenance,
	ReasoningEngineFreshness,
	ReasoningEngineGovernance,
	ReasoningEngineContext,
	ReasoningObjective,
	ReasoningConstraint,
	ReasoningAssumption,
	ReasoningEvidence,
	ReasoningDecisionPoint,
	ReasoningOutcome,
	ReasoningSummary,
	ReasoningPlan,
	ReasoningEngineStageState,
	ReasoningOutput,
	ReasoningEngineRegistration,
	ReasoningEngineRuntimeHealth,
} from './reasoning'

// Strategic reasoning foundation
export {
	StrategicReasoningRegistry,
	StrategicReasoningManager,
} from './strategicReasoning'
export type {
	StrategicReasoningMetadata,
	StrategicReasoningDiagnostics,
	StrategicReasoningSession,
	StrategicOwnership,
	StrategicProvenance,
	StrategicFreshness,
	StrategicGovernance,
	StrategicReasoningContext,
	StrategicObjective,
	StrategicProblem,
	StrategicConstraint,
	StrategicAssumption,
	StrategicOpportunity,
	StrategicRisk,
	StrategicScenario,
	StrategicOutcome,
	StrategicRecommendation,
	StrategicPlanningModel,
	StrategicThinkingStageState,
	StrategicReasoningRegistration,
	StrategicReasoningRuntimeHealth,
} from './strategicReasoning'

// Tactical planning foundation
export {
	TacticalPlanningRegistry,
	TacticalPlanningManager,
} from './tacticalPlanning'
export type {
	TacticalPlanningMetadata,
	TacticalPlanningDiagnostics,
	TacticalPlanningSession,
	TacticalOwnership,
	TacticalProvenance,
	TacticalFreshness,
	TacticalGovernance,
	TacticalPlanningContext,
	TacticalObjective,
	TacticalTask,
	TacticalMilestone,
	TacticalDependency,
	TacticalConstraint,
	TacticalResource,
	TacticalSchedule,
	TacticalOutcome,
	TacticalRecommendation,
	TacticalPlan,
	TacticalPlanningStageState,
	TacticalPlanningRegistration,
	TacticalPlanningRuntimeHealth,
} from './tacticalPlanning'

// Decision intelligence foundation
export {
	DecisionIntelligenceRegistry,
	DecisionIntelligenceManager,
} from './decisionIntelligence'
export type {
	DecisionIntelligenceMetadata,
	DecisionIntelligenceDiagnostics,
	DecisionIntelligenceSession,
	DecisionOwnership as RuntimeDecisionOwnership,
	DecisionProvenance,
	DecisionFreshness,
	DecisionGovernance,
	DecisionIntelligenceContext,
	DecisionCandidate,
	DecisionOption,
	DecisionConstraint,
	DecisionRisk,
	DecisionTradeoff,
	DecisionImpact as RuntimeDecisionImpact,
	DecisionRecommendation,
	DecisionOutcome,
	DecisionSummary,
	DecisionLifecycleState as RuntimeDecisionLifecycleState,
	DecisionPackage,
	DecisionIntelligenceRegistration,
	DecisionIntelligenceRuntimeHealth,
} from './decisionIntelligence'

// Action intelligence foundation
export {
	ActionIntelligenceRegistry,
	ActionIntelligenceManager,
} from './actionIntelligence'
export type {
	ActionIntelligenceMetadata,
	ActionIntelligenceDiagnostics,
	ActionIntelligenceSession,
	ActionOwnership,
	ActionProvenance,
	ActionFreshness,
	ActionGovernance,
	ActionIntelligenceContext,
	ActionPriority,
	ActionGroup,
	ActionItem,
	ActionDependency,
	ActionConstraint,
	ActionAssignment,
	ActionMilestone,
	ActionOutcome,
	ActionSummary,
	ActionLifecycleState,
	ActionPlan,
	ActionIntelligenceRegistration,
	ActionIntelligenceRuntimeHealth,
} from './actionIntelligence'

// Autonomous workflow foundation
export {
	AutonomousWorkflowRegistry,
	AutonomousWorkflowManager,
} from './autonomousWorkflow'
export type {
	AutonomousWorkflowMetadata,
	AutonomousWorkflowDiagnostics,
	AutonomousWorkflowSession,
	WorkflowOwnership,
	WorkflowProvenance,
	WorkflowFreshness,
	WorkflowGovernance,
	AutonomousWorkflowContext,
	WorkflowObjective,
	WorkflowPhase,
	WorkflowStep as AutonomousWorkflowStep,
	WorkflowDependency,
	WorkflowConstraint,
	WorkflowCheckpoint,
	WorkflowApproval,
	WorkflowOutcome,
	WorkflowSummary,
	WorkflowCreatedState,
	WorkflowPlannedState,
	WorkflowReadyState,
	WorkflowRunningState,
	WorkflowWaitingState,
	WorkflowPausedState,
	WorkflowResumedState,
	WorkflowCompletedState,
	WorkflowCancelledState,
	WorkflowFailedState,
	WorkflowLifecycleStateModel,
	AutonomousWorkflowLifecycleState,
	AutonomousWorkflow,
	AutonomousWorkflowRegistration,
	AutonomousWorkflowRuntimeHealth,
} from './autonomousWorkflow'

// Autonomous task foundation
export {
	AutonomousTaskRegistry,
	AutonomousTaskManager,
} from './autonomousTask'
export type {
	AutonomousTaskMetadata,
	AutonomousTaskDiagnostics,
	AutonomousTaskSession,
	TaskOwnership,
	TaskProvenance,
	TaskFreshness,
	TaskGovernance,
	AutonomousTaskContext,
	TaskObjective,
	TaskGroup,
	AutonomousTask,
	TaskDependency,
	TaskConstraint,
	TaskCheckpoint,
	TaskAssignment,
	TaskApproval,
	TaskOutcome,
	TaskSummary,
	TaskCreatedState,
	TaskPlannedState,
	TaskReadyState,
	TaskAssignedState,
	TaskWaitingState,
	TaskRunningState,
	TaskPausedState,
	TaskCompletedState,
	TaskFailedState,
	TaskCancelledState,
	TaskLifecycleStateModel,
	AutonomousTaskLifecycleState,
	AutonomousTaskPlan,
	AutonomousTaskRegistration,
	AutonomousTaskRuntimeHealth,
} from './autonomousTask'

// Autonomous agent foundation
export {
	AutonomousAgentRegistry,
	AutonomousAgentManager,
} from './autonomousAgent'
export type {
	AutonomousAgentMetadata,
	AutonomousAgentDiagnostics,
	AutonomousAgentSession,
	AgentOwnership,
	AgentProvenance,
	AgentFreshness,
	AgentGovernance,
	AutonomousAgentContext,
	AgentRole,
	AgentCapability,
	AgentAssignment,
	AgentResponsibility,
	AgentDependency,
	AgentCommunication,
	AgentDecision,
	AgentOutcome,
	AgentSummary,
	AutonomousAgent,
	AgentRegisteredState,
	AgentAvailableState,
	AgentAssignedState,
	AgentWorkingState,
	AgentWaitingState,
	AgentReviewingState,
	AgentCompletedState,
	AgentSuspendedState,
	AgentFailedState,
	AgentRetiredState,
	AgentLifecycleStateModel,
	AutonomousAgentLifecycleState,
	CoordinationPlan,
	CoordinationGroup,
	CoordinationQueue,
	CoordinationCheckpoint,
	CoordinationDependency,
	CoordinationConflict,
	CoordinationResolution,
	CoordinationAudit,
	AutonomousAgentRegistration,
	AutonomousAgentRuntimeHealth,
} from './autonomousAgent'

// Autonomous project foundation
export {
	AutonomousProjectRegistry,
	AutonomousProjectManager,
} from './autonomousProject'
export type {
	AutonomousProjectMetadata,
	AutonomousProjectDiagnostics,
	AutonomousProjectSession,
	ProjectOwnership,
	ProjectProvenance,
	ProjectFreshness,
	ProjectGovernance,
	AutonomousProjectContext,
	ProjectPortfolio,
	ProjectMilestone,
	ProjectDependency,
	ProjectConstraint,
	ProjectResource,
	ProjectRisk,
	ProjectDecision,
	ProjectOutcome,
	ProjectSummary,
	ProjectCreatedState,
	ProjectPlannedState,
	ProjectCoordinatingState,
	ProjectReadyState,
	ProjectRunningState,
	ProjectReviewingState,
	ProjectCompletedState,
	ProjectBlockedState,
	ProjectFailedState,
	ProjectCancelledState,
	ProjectLifecycleStateModel,
	AutonomousProjectLifecycleState,
	ProjectCoordination,
	AutonomousProjectPlan,
	AutonomousProjectRegistration,
	AutonomousProjectRuntimeHealth,
} from './autonomousProject'

// Autonomous workspace foundation
export {
	AutonomousWorkspaceRegistry,
	AutonomousWorkspaceManager,
} from './autonomousWorkspace'
export type {
	AutonomousWorkspaceMetadata,
	AutonomousWorkspaceDiagnostics,
	AutonomousWorkspaceSession,
	WorkspaceOwnership,
	WorkspaceProvenance,
	WorkspaceFreshness,
	WorkspaceGovernance,
	AutonomousWorkspaceContext,
	WorkspaceProfile,
	WorkspaceConfiguration,
	WorkspaceSnapshot,
	WorkspaceState,
	WorkspaceSession,
	WorkspaceResource,
	WorkspaceEnvironment,
	WorkspaceLayout,
	WorkspaceSummary,
	WorkspaceOutcome,
	IDEInstance,
	TerminalInstance,
	BrowserInstance,
	ApplicationInstance,
	WindowInstance,
	WorkspaceProcess,
	WorkspaceService,
	WorkspaceConnection,
	WorkspaceDependency,
	WorkspaceCheckpoint,
	WorkspaceCreatedState,
	WorkspaceConfiguredState,
	WorkspaceReadyState,
	WorkspaceActiveState,
	WorkspaceSuspendedState,
	WorkspaceRestoredState,
	WorkspaceArchivedState,
	WorkspaceClosedState,
	WorkspaceFailedState,
	WorkspaceRecoveredState,
	WorkspaceLifecycleStateModel,
	AutonomousWorkspaceLifecycleState,
	WorkspaceResourceSnapshot,
	AutonomousWorkspaceRegistration,
	AutonomousWorkspaceRuntimeHealth,
} from './autonomousWorkspace'

// Autonomous recovery foundation
export {
	AutonomousRecoveryRegistry,
	AutonomousRecoveryManager,
} from './autonomousRecovery'
export type {
	AutonomousRecoveryMetadata,
	AutonomousRecoveryDiagnostics,
	AutonomousRecoverySession,
	RecoveryOwnership,
	RecoveryProvenance,
	RecoveryFreshness,
	RecoveryGovernance,
	AutonomousRecoveryContext,
	RecoveryPlan,
	RecoveryCheckpoint,
	RecoverySnapshot,
	RecoveryState,
	RecoveryDependency,
	RecoveryStrategy,
	RecoveryTimeline,
	RecoveryRecommendation,
	RecoveryOutcome,
	RecoverySummary,
	SessionContinuityPlan,
	SessionSnapshot,
	SessionRestorePoint,
	WorkspaceRestorePlan,
	RuntimeRestorePlan,
	ServiceRestorePlan,
	ExecutionResumePlan,
	ContinuityAudit,
	RecoveryDetectedState,
	RecoveryPlannedState,
	RecoveryPreparedState,
	RecoveryReadyState,
	RecoveryInProgressState,
	RecoveryValidatedState,
	RecoveryCompletedState,
	RecoveryFailedState,
	RecoveryCancelledState,
	RecoveryArchivedState,
	RecoveryLifecycleStateModel,
	AutonomousRecoveryLifecycleState,
	AutonomousRecoveryRegistration,
	AutonomousRecoveryRuntimeHealth,
} from './autonomousRecovery'

// Desktop integration architecture foundation
export {
	DesktopIntegrationRegistry,
	DesktopIntegrationManager,
} from './desktopIntegration'
export type {
	DesktopIntegrationMetadata,
	DesktopIntegrationDiagnostics,
	DesktopIntegrationSession,
	DesktopOwnership,
	DesktopProvenance,
	DesktopFreshness,
	DesktopGovernance,
	DesktopIntegrationContext,
	DesktopProfile,
	DesktopEnvironment,
	DesktopApplication,
	DesktopWorkspace,
	DesktopWindow,
	DesktopProcess,
	DesktopSession,
	DesktopCapability,
	DesktopSummary,
	IDETarget,
	BrowserTarget,
	TerminalTarget,
	ApplicationTarget,
	ServiceTarget,
	ProcessTarget,
	WorkspaceTarget,
	WindowTarget,
	AutomationTarget,
	IntegrationDependency,
	IntegrationTarget,
	DesktopConfiguration,
	DesktopRegisteredState,
	DesktopAvailableState,
	DesktopPreparedState,
	DesktopReadyState,
	DesktopConnectedState,
	DesktopSuspendedState,
	DesktopDisconnectedState,
	DesktopRecoveredState,
	DesktopFailedState,
	DesktopArchivedState,
	DesktopLifecycleStateModel,
	DesktopIntegrationState,
	DesktopIntegrationLifecycleState,
	DesktopIntegrationRegistration,
	DesktopIntegrationRuntimeHealth,
} from './desktopIntegration'

// IDE integration architecture foundation
export {
	IDEIntegrationRegistry,
	IDEIntegrationManager,
} from './ideIntegration'
export type {
	IDEIntegrationMetadata,
	IDEIntegrationDiagnostics,
	IDEIntegrationSession,
	IDEOwnership,
	IDEProvenance,
	IDEFreshness,
	IDEGovernance,
	IDEIntegrationContext,
	IDEProfile,
	IDEWorkspace,
	IDEProject,
	IDEWindow,
	IDEEditor,
	IDETerminal,
	IDEExtension,
	IDECapability,
	IDESummary,
	WorkspaceFolder,
	OpenFile,
	EditorGroup,
	CursorPosition,
	Breakpoint,
	TerminalSession,
	DebugSession,
	TaskRunner,
	IDEProcess,
	IDECheckpoint,
	IDEResource,
	IDEConfiguration,
	IDERegisteredState,
	IDEAvailableState,
	IDEPreparedState,
	IDEReadyState,
	IDEConnectedState,
	IDESuspendedState,
	IDEDisconnectedState,
	IDERecoveredState,
	IDEFailedState,
	IDEArchivedState,
	IDELifecycleStateModel,
	IDEIntegrationState,
	IDEIntegrationLifecycleState,
	IDEIntegrationRegistration,
	IDEIntegrationRuntimeHealth,
} from './ideIntegration'

// Terminal integration architecture foundation
export {
	TerminalIntegrationRegistry,
	TerminalIntegrationManager,
} from './terminalIntegration'
export type {
	TerminalIntegrationMetadata,
	TerminalIntegrationDiagnostics,
	TerminalIntegrationSession,
	TerminalOwnership,
	TerminalProvenance,
	TerminalFreshness,
	TerminalGovernance,
	TerminalIntegrationContext,
	TerminalProfile,
	TerminalEnvironment,
	TerminalWorkspace,
	TerminalWindow,
	TerminalInstance as TerminalIntegrationInstance,
	TerminalConfiguration,
	TerminalCapability,
	TerminalShell,
	TerminalCommand,
	TerminalSummary,
	ShellSession,
	ShellProfile,
	CommandQueue,
	CommandHistory,
	WorkingDirectory,
	EnvironmentVariable,
	ProcessHandle,
	ConsoleBuffer,
	TerminalCheckpoint,
	TerminalSnapshot,
	TerminalResource,
	TerminalRegisteredState,
	TerminalAvailableState,
	TerminalPreparedState,
	TerminalReadyState,
	TerminalConnectedState,
	TerminalBusyState,
	TerminalWaitingState,
	TerminalSuspendedState,
	TerminalFailedState,
	TerminalArchivedState,
	TerminalLifecycleStateModel,
	TerminalIntegrationState,
	TerminalIntegrationLifecycleState,
	TerminalIntegrationRegistration,
	TerminalIntegrationRuntimeHealth,
} from './terminalIntegration'

// Browser integration architecture foundation
export {
	BrowserIntegrationRegistry,
	BrowserIntegrationManager,
} from './browserIntegration'
export type {
	BrowserIntegrationMetadata,
	BrowserIntegrationDiagnostics,
	BrowserIntegrationSession,
	BrowserOwnership,
	BrowserProvenance,
	BrowserFreshness,
	BrowserGovernance,
	BrowserIntegrationContext,
	BrowserProfile,
	BrowserEnvironment,
	BrowserWindow,
	BrowserSession,
	BrowserTab,
	BrowserConfiguration,
	BrowserCapability,
	BrowserExtension,
	BrowserBookmark,
	BrowserSummary,
	WebPage,
	URLReference,
	NavigationHistory,
	CookieStore,
	LocalStorageReference,
	SessionStorageReference,
	BrowserDeveloperTools,
	BrowserNetworkSession,
	BrowserCheckpoint,
	BrowserSnapshot,
	BrowserResource,
	BrowserRegisteredState,
	BrowserAvailableState,
	BrowserPreparedState,
	BrowserReadyState,
	BrowserConnectedState,
	BrowserActiveState,
	BrowserSuspendedState,
	BrowserDisconnectedState,
	BrowserFailedState,
	BrowserArchivedState,
	BrowserLifecycleStateModel,
	BrowserIntegrationState,
	BrowserIntegrationLifecycleState,
	BrowserIntegrationRegistration,
	BrowserIntegrationRuntimeHealth,
} from './browserIntegration'

// Git integration architecture foundation
export {
	GitIntegrationRegistry,
	GitIntegrationManager,
} from './gitIntegration'
export type {
	GitIntegrationMetadata,
	GitIntegrationDiagnostics,
	GitIntegrationSession,
	GitOwnership,
	GitProvenance,
	GitFreshness,
	GitGovernance,
	GitIntegrationContext,
	GitRepository,
	GitBranch,
	GitCommit,
	GitTag,
	GitRemote,
	GitWorkspace,
	GitConfiguration,
	GitCapability,
	GitIdentity,
	GitSummary,
	StagingArea,
	CommitHistory,
	BranchGraph,
	MergeRequest,
	MergeConflict,
	RepositorySnapshot,
	WorkingTree,
	FileChange,
	GitCheckpoint,
	RepositoryState,
	GitResource,
	RepositoryRegisteredState,
	RepositoryAvailableState,
	RepositoryPreparedState,
	RepositoryReadyState,
	RepositoryActiveState,
	RepositorySyncPendingState,
	RepositorySuspendedState,
	RepositoryArchivedState,
	RepositoryFailedState,
	RepositoryRecoveredState,
	GitLifecycleStateModel,
	GitIntegrationState,
	GitIntegrationLifecycleState,
	GitIntegrationRegistration,
	GitIntegrationRuntimeHealth,
} from './gitIntegration'

// Source control orchestration architecture foundation
export {
	SourceControlRegistry,
	SourceControlManager,
} from './sourceControl'
export type {
	SourceControlMetadata,
	SourceControlDiagnostics,
	SourceControlSession,
	SourceControlOwnership,
	SourceControlProvenance,
	SourceControlFreshness,
	SourceControlGovernance,
	SourceControlContext,
	RepositoryWorkspace,
	RepositoryGroup,
	BranchStrategy,
	CommitStrategy,
	MergeStrategy,
	ReleaseStrategy,
	RepositoryPolicy,
	RepositoryGovernance,
	SourceControlCapability,
	SourceControlSummary,
	SourceControlState,
	RepositoryPlan,
	BranchPlan,
	CommitPlan,
	MergePlan,
	ReleasePlan,
	SynchronizationPlan,
	ConflictResolutionPlan,
	RepositoryCheckpoint,
	RepositoryAudit,
	SourceControlResource,
	SourceControlConfiguration,
	SourceControlPlannedState,
	SourceControlPreparedState,
	SourceControlReadyState,
	SourceControlPendingState,
	SourceControlActiveState,
	SourceControlWaitingState,
	SourceControlSuspendedState,
	SourceControlCompletedState,
	SourceControlFailedState,
	SourceControlArchivedState,
	SourceControlLifecycleStateModel,
	SourceControlLifecycleState,
	SourceControlRegistration,
	SourceControlRuntimeHealth,
} from './sourceControl'

// Repository intelligence architecture foundation
export {
	RepositoryIntelligenceRegistry,
	RepositoryIntelligenceManager,
} from './repositoryIntelligence'
export type {
	RepositoryIntelligenceMetadata,
	RepositoryIntelligenceDiagnostics,
	RepositoryIntelligenceSession,
	RepositoryIntelligenceOwnership,
	RepositoryIntelligenceProvenance,
	RepositoryIntelligenceFreshness,
	RepositoryIntelligenceGovernance,
	RepositoryIntelligenceContext,
	RepositoryProfile,
	RepositoryTopology,
	RepositoryMetrics,
	RepositoryHealth,
	RepositoryQuality,
	RepositoryDependencyGraph,
	RepositoryKnowledgeMap,
	RepositoryRiskProfile,
	RepositoryEvolution,
	RepositoryIntelligenceSummary,
	RepositoryIntelligenceState,
	RepositoryAnalysisPlan,
	ArchitectureAnalysis,
	DependencyAnalysis,
	QualityAnalysis,
	ComplexityAnalysis,
	TechnicalDebtAnalysis,
	ChangeAnalysis,
	RepositoryInsight,
	RepositoryRecommendation,
	RepositoryIntelligenceAudit,
	RepositoryIntelligenceResource,
	RepositoryIntelligenceConfiguration,
	RepositoryIntelligenceRegisteredState,
	RepositoryIntelligenceIndexedState,
	RepositoryIntelligenceAnalysedState,
	RepositoryIntelligenceAssessedState,
	RepositoryIntelligenceClassifiedState,
	RepositoryIntelligenceReviewedState,
	RepositoryIntelligenceApprovedState,
	RepositoryIntelligencePublishedState,
	RepositoryIntelligenceArchivedState,
	RepositoryIntelligenceDeprecatedState,
	RepositoryIntelligenceLifecycleStateModel,
	RepositoryIntelligenceLifecycleState,
	RepositoryIntelligenceRegistration,
	RepositoryIntelligenceRuntimeHealth,
} from './repositoryIntelligence'

// Execution readiness foundation
export {
	ExecutionReadinessRegistry,
	ExecutionReadinessManager,
} from './executionReadiness'
export type {
	ExecutionReadinessMetadata,
	ExecutionReadinessDiagnostics,
	ExecutionReadinessSession,
	ExecutionOwnership,
	ExecutionProvenance,
	ExecutionFreshness,
	ExecutionReadinessGovernance,
	ExecutionReadinessContext,
	ExecutionReadinessStatus,
	ExecutionReadinessDecision,
	ExecutionReadinessCriteria,
	ExecutionReadinessRecommendation,
	ExecutionReadinessEvidence,
	ExecutionReadinessTraceability,
	ExecutionReadinessSummary,
	ExecutionReadinessReport,
	ExecutableActionPackage,
	ExecutableWorkflowPackage,
	ExecutableContextPackage,
	ExecutableConstraintPackage,
	ExecutableValidationPackage,
	ExecutionApprovalPackage,
	ExecutionAuditPackage,
	ExecutionReadyPackage,
	ActionCompletionPolicy,
	DependencyCompletionPolicy,
	ValidationCompletionPolicy,
	ApprovalCompletionPolicy,
	WorkflowReadinessPolicy,
	ExecutionSafetyPolicy,
	ExecutionReadinessPolicy,
	ExecutionReadinessRegistration,
	ExecutionReadinessRuntimeHealth,
} from './executionReadiness'

// Workflow engine foundation
export {
	WorkflowRegistry,
	WorkflowEngineManager,
} from './workflow'
export type {
	WorkflowStep,
	WorkflowArtifact,
	RuntimeWorkflowGovernance,
	WorkflowMetadata,
	RuntimeWorkflowDiagnostic,
	WorkflowDefinition,
	WorkflowInstance,
	WorkflowContext,
	WorkflowEngineHealth,
} from './workflow'

// Runtime Context
export { RuntimeContextFactory } from './context'
export type { RuntimeContext } from './context'

// Lifecycle
export { LifecycleManager } from './lifecycle'
export type { LifecyclePhase, LifecycleHandler, LifecycleEvent } from './lifecycle'

// Health Framework
export { HealthFramework, StandardHealthChecks } from './health'
export type { HealthStatus, HealthCheckResult, ComponentHealth, RuntimeHealthReport, HealthCheck } from './health'

// Configuration Loader
export { RuntimeConfigurationLoader } from './configLoader'
export type { RuntimeConfiguration } from './configLoader'

// Module Loader
export { RuntimeModuleLoader } from './moduleLoader'
export type { RuntimeModuleMetadata, RuntimeModule } from './moduleLoader'

// VAIOS Kernel
export { VaiosKernel } from './kernel'

// Re-export configuration contracts
export type { VaiosCoreConfig, TenantPolicyConfig, FeatureFlagConfig } from '@/lib/ai-framework/config/contracts'
export type { VaiosEnvironment } from '@/lib/ai-framework/config/contracts'
