import { buildEnterpriseCampaignSpec, buildEnterpriseImagePrompt } from '@/lib/enterpriseCreativeEngine'
import { generateGoogleAdsCampaignPlan } from '@/lib/googleAdsPlanGenerator'
import type { GoogleAdsBuilderPrefill } from '@/lib/executionPrefill'
import type {
  VyronActionQueueItem,
  VyronClient,
  VyronCreative,
  VyronKeyword,
  VyronStore,
} from '@/lib/vyronStore/types'

export const DEMO_ENVIRONMENT_VERSION = 2
export const DEMO_CLIENT_IDS = {
  vyron: 'demo-client-vyron-core',
  bridgewater: 'demo-client-bridgewater',
  cuisine: 'demo-client-cutting-edge',
} as const

const T = '2025-04-15T08:00:00.000Z'
const T2 = '2025-04-20T10:00:00.000Z'
const T3 = '2025-05-01T09:00:00.000Z'

export function isDemoEnvironmentLoaded(store: VyronStore): boolean {
  return store.clients.some(c => c.id === DEMO_CLIENT_IDS.vyron)
}

export function shouldSeedDemoEnvironment(store: VyronStore): boolean {
  if (isDemoEnvironmentLoaded(store)) return false
  return (
    store.clients.length === 0 &&
    store.keywords.length === 0 &&
    store.creatives.length === 0 &&
    store.actionQueue.length === 0
  )
}

function kw(
  id: string,
  keyword: string,
  volume: number,
  difficulty: number,
  intent: VyronKeyword['intent'],
  forecast: string,
  gap: string,
  business: string,
  industry: string,
  targetArea: string,
): VyronKeyword {
  return {
    id,
    keyword,
    volume,
    difficulty,
    intent,
    forecast,
    gap,
    recommendedPage: `/solutions/${keyword.split(' ')[0]}`,
    business,
    industry,
    targetArea,
  }
}

function creative(
  partial: Omit<VyronCreative, 'createdAt' | 'updatedAt'>,
): VyronCreative {
  const now = T3
  return { ...partial, createdAt: now, updatedAt: now }
}

function enterpriseCreative(
  partial: Omit<VyronCreative, 'createdAt' | 'updatedAt' | 'campaignSpec' | 'imagePrompt' | 'headline' | 'cta' | 'visualDirection'>,
  builder: import('@/lib/vyronStore/types').CreativeBuilderInput,
  version: number,
): VyronCreative {
  const spec = buildEnterpriseCampaignSpec(builder, version)
  const imagePrompt = buildEnterpriseImagePrompt(spec, builder, version)
  return creative({
    ...partial,
    headline: spec.headline,
    cta: spec.cta,
    imagePrompt,
    visualDirection: `${spec.layout} · ${spec.theme}`,
    campaignSpec: spec,
  })
}

function adsPlan(
  id: string,
  form: GoogleAdsBuilderPrefill,
  settings: VyronStore['settings'],
  launched: boolean,
  actionId?: string,
) {
  const plan = generateGoogleAdsCampaignPlan(form, settings)
  return {
    id,
    campaignName: form.campaignName,
    dailyBudget: form.dailyBudget,
    targetArea: form.targetArea,
    keywordTheme: form.keywordTheme,
    productService: form.productService,
    audience: form.audience,
    offer: form.offer,
    landingPageUrl: form.landingPageUrl,
    planText: plan.fullPlan,
    launched,
    createdAt: T2,
    actionId,
  }
}

export function createDemoEnvironment(): VyronStore {
  const settings: VyronStore['settings'] = {
    businessName: 'VYRON Agency OS',
    defaultProject: 'VYRON CORE',
    defaultMarket: 'South Africa',
    defaultAdDailyBudget: 500,
    defaultSeoTimelineMonths: 6,
    contactEmail: 'agency@vyronreach.local',
    businessType: 'AI Marketing Agency — multi-client',
    defaultTargetArea: 'South Africa',
    aiMarketingRules:
      'Demo environment: 3 live clients. SEO 6-month horizon. Google Ads test budgets per client. Scale only after rankings + lead proof. Creatives require client approval before launch.',
  }

  const clients: VyronClient[] = [
    {
      id: DEMO_CLIENT_IDS.vyron,
      businessName: 'VYRON CORE',
      industry: 'Workforce Management SaaS',
      website: 'https://vyron.co.za',
      monthlyMarketingBudget: 15000,
      targetArea: 'South Africa',
      targetKeywords: [
        'workforce management software South Africa',
        'staff clocking system',
        'employee attendance software',
        'payroll ready clocking system',
        'AI HR software',
        'rostering software',
      ],
      notes:
        'Primary SaaS growth account. Focus: qualified demos from HR managers and business owners. Pair SEO authority with R500/day Google Search tests.',
      plan: 'SEO 6mo + Google Search R500/day + LinkedIn retargeting after 30 days',
      adSpendNote: 'R15,000/mo — R9k SEO/content, R6k paid (Search-first)',
      createdAt: T,
    },
    {
      id: DEMO_CLIENT_IDS.bridgewater,
      businessName: 'BRIDGEWATER BOTANICALS',
      industry: 'Non-alcoholic botanical beverage',
      website: 'https://bridgewaterbotanicals.co.za',
      monthlyMarketingBudget: 8000,
      targetArea: 'Cape Town + Johannesburg',
      targetKeywords: [
        'non alcoholic botanical drink',
        'sober alternative drink',
        'alcohol free social drink',
        'botanical relaxation drink',
        'premium non alcoholic beverage',
      ],
      notes:
        'Premium lifestyle brand. Meta + Google Display for awareness; shopping campaigns after creative approval. Mood: luxury botanical, evening social.',
      plan: 'Brand awareness Q2 + DTC trial packs Cape Town & JHB',
      adSpendNote: 'R8,000/mo — R4k social/video, R2.5k display, R1.5k content',
      createdAt: T,
    },
    {
      id: DEMO_CLIENT_IDS.cuisine,
      businessName: 'CUTTING EDGE CUISINE',
      industry: 'Food & catering',
      website: 'https://cuttingedgecuisine.co.za',
      monthlyMarketingBudget: 12000,
      targetArea: 'Cape Town',
      targetKeywords: [
        'corporate catering Cape Town',
        'sushi catering',
        'office lunch catering',
        'event catering Cape Town',
        'premium catering company',
      ],
      notes:
        'B2B corporate catering leads. Showcase sushi platters and premium lunch setups. Google Local + Search for “corporate catering Cape Town”.',
      plan: 'Local SEO + Google Search R400/day + LinkedIn corporate outreach',
      adSpendNote: 'R12,000/mo — R5k paid search, R4k content/social, R3k SEO local',
      createdAt: T,
    },
  ]

  const keywords: VyronKeyword[] = [
    ...clients[0].targetKeywords.map((k, i) =>
      kw(
        `demo-kw-vyron-${i}`,
        k,
        1200 - i * 80,
        28 + i * 3,
        i < 2 ? 'Buyer Intent' : 'Commercial',
        i < 3 ? 'Top 10 in 4–6 months' : 'Top 20 in 6 months',
        i === 0 ? 'Competitor weak on payroll-ready messaging' : 'Add comparison landing section',
        'VYRON CORE',
        'Workforce Management SaaS',
        'South Africa',
      ),
    ),
    ...clients[1].targetKeywords.map((k, i) =>
      kw(
        `demo-kw-bridge-${i}`,
        k,
        900 - i * 60,
        22 + i * 4,
        i < 2 ? 'Commercial' : 'Informational',
        'Top 15 in 5 months',
        'Lifestyle blogs lack premium sober positioning',
        'BRIDGEWATER BOTANICALS',
        'Botanical beverage',
        'Cape Town + Johannesburg',
      ),
    ),
    ...clients[2].targetKeywords.map((k, i) =>
      kw(
        `demo-kw-cuisine-${i}`,
        k,
        700 - i * 50,
        25 + i * 2,
        'Local',
        'Map pack + top 10 in 3 months',
        'Weak competitor pages for sushi corporate catering',
        'CUTTING EDGE CUISINE',
        'Catering',
        'Cape Town',
      ),
    ),
  ]

  const rankings = keywords.map((k, i) => ({
    id: `demo-rank-${i}`,
    keyword: k.keyword,
    page: k.recommendedPage ?? '/',
    position: 18 + (i % 12),
    change: i % 3 === 0 ? -4 : i % 3 === 1 ? 2 : 0,
    forecast: k.forecast,
    stuck: i % 4 === 0,
    previousPosition: 22 + (i % 10),
  }))

  const competitors = [
    {
      id: 'demo-comp-1',
      name: 'WorkforceMax SA',
      domain: 'workforcemax.example',
      weakPages: ['/pricing', '/features/time-tracking'],
      keywordGaps: ['payroll ready clocking', 'AI HR alerts'],
      threat: 'Medium' as const,
    },
    {
      id: 'demo-comp-2',
      name: 'SoberSip Co',
      domain: 'sobersip.example',
      weakPages: ['/shop', '/about'],
      keywordGaps: ['botanical relaxation drink', 'premium non alcoholic'],
      threat: 'Low' as const,
    },
    {
      id: 'demo-comp-3',
      name: 'Cape Cater Hub',
      domain: 'capecaterhub.example',
      weakPages: ['/corporate', '/menu'],
      keywordGaps: ['sushi catering Cape Town', 'office lunch catering'],
      threat: 'High' as const,
    },
  ]

  const contentTasks = [
    { id: 'demo-ct-1', title: 'Workforce Management Software SA — Buyer Guide', type: 'Blog' as const, status: 'Ready' as const, targetKeyword: keywords[0].keyword },
    { id: 'demo-ct-2', title: 'VYRON CORE — Demo Landing Page', type: 'Landing Page' as const, status: 'Published' as const, targetKeyword: keywords[0].keyword },
    { id: 'demo-ct-3', title: 'Payroll-Ready Clocking FAQ', type: 'FAQ' as const, status: 'AI Generated' as const, targetKeyword: keywords[3].keyword },
    { id: 'demo-ct-4', title: 'Sober Social — Bridgewater Brand Story', type: 'Blog' as const, status: 'Ready' as const, targetKeyword: keywords[6].keyword },
    { id: 'demo-ct-5', title: 'Corporate Catering Cape Town — Service Page', type: 'Landing Page' as const, status: 'Ready' as const, targetKeyword: keywords[11].keyword },
    { id: 'demo-ct-6', title: 'Sushi Office Lunch — LinkedIn Carousel Copy', type: 'Blog' as const, status: 'Draft' as const, targetKeyword: keywords[12].keyword },
  ]

  const campaigns = [
    { id: 'demo-camp-1', platform: 'Google Search', dailyBudget: 500, monthlyBudget: 15000, status: 'Active' as const, wastedSpend: 420, intentScore: 88, notes: 'VYRON CORE — buyer intent exact match' },
    { id: 'demo-camp-2', platform: 'Meta + Display', dailyBudget: 267, monthlyBudget: 8000, status: 'Testing' as const, wastedSpend: 180, intentScore: 72, notes: 'Bridgewater awareness — Cape Town & JHB' },
    { id: 'demo-camp-3', platform: 'Google Search Local', dailyBudget: 400, monthlyBudget: 12000, status: 'Active' as const, wastedSpend: 310, intentScore: 91, notes: 'Cutting Edge — corporate catering Cape Town' },
  ]

  const vyronAdsForm: GoogleAdsBuilderPrefill = {
    campaignName: 'VYRON CORE — Workforce SaaS Search',
    dailyBudget: 500,
    targetArea: 'South Africa',
    productService: 'Workforce management software',
    keywordTheme: 'workforce management software South Africa',
    audience: 'South African business owners, ops managers, HR managers (50–500 staff)',
    offer: 'Stop losing payroll hours — AI clocking, rostering & HR alerts. Book a demo.',
    landingPageUrl: 'https://vyron.co.za/workforce-management',
  }

  const bridgeAdsForm: GoogleAdsBuilderPrefill = {
    campaignName: 'Bridgewater — Premium Botanical Awareness',
    dailyBudget: 267,
    targetArea: 'Cape Town, Johannesburg',
    productService: 'Non-alcoholic botanical beverages',
    keywordTheme: 'premium non alcoholic beverage',
    audience: 'Urban professionals 25–45, sober-curious, premium lifestyle',
    offer: 'Wind down without alcohol — botanical relaxation in a glass. Shop the range.',
    landingPageUrl: 'https://bridgewaterbotanicals.co.za/shop',
  }

  const cuisineAdsForm: GoogleAdsBuilderPrefill = {
    campaignName: 'Cutting Edge — Corporate Catering Cape Town',
    dailyBudget: 400,
    targetArea: 'Cape Town',
    productService: 'Corporate catering & sushi platters',
    keywordTheme: 'corporate catering Cape Town',
    audience: 'Office managers, EA’s, event planners — CBD & Atlantic Seaboard corporates',
    offer: 'Premium sushi & lunch catering for teams of 10–200. Same-week booking.',
    landingPageUrl: 'https://cuttingedgecuisine.co.za/corporate',
  }

  const googleAdsPlans = [
    adsPlan('demo-plan-vyron', vyronAdsForm, settings, true, 'demo-act-vyron-ads'),
    adsPlan('demo-plan-bridge', bridgeAdsForm, settings, false, 'demo-act-bridge-ads'),
    adsPlan('demo-plan-cuisine', cuisineAdsForm, settings, true, 'demo-act-cuisine-ads'),
  ]

  const vyronBuilder = (platform: import('@/lib/vyronStore/types').CreativePlatform, version: number) => ({
    clientId: DEMO_CLIENT_IDS.vyron,
    clientName: 'VYRON CORE',
    productName: 'VYRON Workforce Command Centre',
    campaignGoal: 'Generate leads for workforce management software',
    platform,
    audience: 'South African business owners & HR managers',
    offer: 'Stop losing payroll hours — one dashboard for clocking, rostering & HR alerts',
    headline: 'VYRON CORE IS LIVE',
    cta: 'BOOK DEMO',
    visualStyle: 'Premium SaaS' as const,
    colourDirection: 'navy neon cyan purple',
    notes: 'Enterprise SaaS launch — gold standard',
    layout: 'SaaS Launch Campaign' as const,
    variationTheme: (['Futuristic AI', 'Executive Enterprise', 'South African Market Focus'] as const)[version - 1],
    website: 'vyron.co.za',
    contact: 'hello@vyron.co.za · +27 21 000 0000',
  })

  const creatives: VyronCreative[] = [
    enterpriseCreative(
      {
        id: 'demo-cr-vyron-1',
        clientId: DEMO_CLIENT_IDS.vyron,
        clientName: 'VYRON CORE',
        productName: 'VYRON Workforce Command Centre',
        campaignGoal: 'Generate leads for workforce management software',
        platform: 'Facebook',
        audience: 'South African business owners & HR managers',
        offer: 'Stop losing payroll hours — one dashboard for clocking, rostering & HR alerts',
        visualStyle: 'Premium SaaS',
        colourDirection: 'blue cyan purple glow',
        notes: 'SaaS dashboard hero — workforce UI',
        version: 1,
        status: 'Approved',
        feedbackNotes: 'Client approved — ready for campaign launch.',
        approvalHistory: [
          { id: 'demo-h-v1', status: 'Awaiting Approval', note: 'Version 1 generated', createdAt: T2 },
          { id: 'demo-h-v2', status: 'Approved', note: 'Campaign Ready — launch Google Ads', createdAt: T3 },
        ],
        actionId: 'demo-act-vyron-creative',
      },
      vyronBuilder('Facebook', 1),
      1,
    ),
    enterpriseCreative(
      {
        id: 'demo-cr-vyron-2',
        clientId: DEMO_CLIENT_IDS.vyron,
        clientName: 'VYRON CORE',
        productName: 'VYRON Workforce Command Centre',
        campaignGoal: 'Generate leads',
        platform: 'LinkedIn',
        audience: 'HR & Operations leaders',
        offer: 'Payroll-ready clocking + AI HR alerts',
        visualStyle: 'Corporate',
        colourDirection: 'navy silver blue',
        notes: 'LinkedIn corporate layout',
        version: 2,
        status: 'Awaiting Approval',
        feedbackNotes: '',
        approvalHistory: [{ id: 'demo-h-v3', status: 'Awaiting Approval', note: 'Version 2 generated', createdAt: T2 }],
      },
      { ...vyronBuilder('LinkedIn', 2), layout: 'LinkedIn Corporate' },
      2,
    ),
    enterpriseCreative(
      {
        id: 'demo-cr-vyron-3',
        clientId: DEMO_CLIENT_IDS.vyron,
        clientName: 'VYRON CORE',
        productName: 'VYRON Workforce Command Centre',
        campaignGoal: 'Retargeting',
        platform: 'Google Display',
        audience: 'Site visitors — demo abandoners',
        offer: '14-day pilot — no credit card',
        visualStyle: 'Futuristic',
        colourDirection: 'dark neon cyan',
        notes: 'Display retargeting',
        version: 3,
        status: 'Revision Requested',
        feedbackNotes: 'Make headline shorter; more premium finish.',
        approvalHistory: [
          { id: 'demo-h-v4', status: 'Revision Requested', note: 'Client wants shorter headline', createdAt: T3 },
        ],
      },
      { ...vyronBuilder('Google Display', 3), layout: 'Billboard' },
      3,
    ),
    creative({
      id: 'demo-cr-bridge-1',
      clientId: DEMO_CLIENT_IDS.bridgewater,
      clientName: 'BRIDGEWATER BOTANICALS',
      productName: 'Bridgewater Botanical Tonics',
      campaignGoal: 'Brand awareness + online sales',
      platform: 'Instagram',
      audience: 'Cape Town & JHB urban professionals, sober-curious',
      offer: 'Premium botanical relaxation — alcohol-free evening ritual',
      headline: 'Wind down. Stay sharp.',
      cta: 'Shop the Range',
      visualStyle: 'Bold',
      colourDirection: 'emerald gold moody luxury',
      notes: 'Glass bottles, nightlife bokeh',
      version: 1,
      status: 'Approved',
      imagePrompt: '# Instagram — Bridgewater\nMoody luxury, glass botanical bottles, gold rim light, social evening scene.',
      visualDirection: 'Botanical luxury · emerald gold · lifestyle',
      feedbackNotes: 'Approved for Meta launch.',
      approvalHistory: [
        { id: 'demo-h-b1', status: 'Approved', note: 'Campaign Ready', createdAt: T3 },
      ],
    }),
    creative({
      id: 'demo-cr-bridge-2',
      clientId: DEMO_CLIENT_IDS.bridgewater,
      clientName: 'BRIDGEWATER BOTANICALS',
      productName: 'Bridgewater Botanical Tonics',
      campaignGoal: 'Awareness',
      platform: 'Facebook',
      audience: 'Premium non-drinkers 25–40',
      offer: 'Sober alternative for social nights',
      headline: 'The sober sip that feels special',
      cta: 'Discover Botanicals',
      visualStyle: 'Minimal',
      colourDirection: 'sage cream copper',
      notes: 'Minimal product on marble',
      version: 2,
      status: 'Awaiting Approval',
      imagePrompt: '# Facebook — Bridgewater\nMinimal marble surface, single bottle, soft botanical shadows.',
      visualDirection: 'Minimal premium · sage · copper accents',
      feedbackNotes: '',
      approvalHistory: [{ id: 'demo-h-b2', status: 'Awaiting Approval', note: 'V2 generated', createdAt: T2 }],
    }),
    creative({
      id: 'demo-cr-bridge-3',
      clientId: DEMO_CLIENT_IDS.bridgewater,
      clientName: 'BRIDGEWATER BOTANICALS',
      productName: 'Bridgewater Botanical Tonics',
      campaignGoal: 'WhatsApp community',
      platform: 'WhatsApp',
      audience: 'Existing customers + VIP list',
      offer: 'Weekend tasting box — 15% off',
      headline: 'Your weekend ritual awaits',
      cta: 'Order on WhatsApp',
      visualStyle: 'Bold',
      colourDirection: 'deep green amber',
      notes: 'WhatsApp status format',
      version: 3,
      status: 'Declined',
      imagePrompt: '# WhatsApp Status — Bridgewater\nVertical bottle shot, weekend lifestyle.',
      visualDirection: 'WhatsApp status · bold offer strip',
      feedbackNotes: 'Too promotional — soften CTA.',
      approvalHistory: [{ id: 'demo-h-b3', status: 'Declined', note: 'CTA too aggressive', createdAt: T3 }],
    }),
    creative({
      id: 'demo-cr-cuisine-1',
      clientId: DEMO_CLIENT_IDS.cuisine,
      clientName: 'CUTTING EDGE CUISINE',
      productName: 'Cutting Edge Corporate Catering',
      campaignGoal: 'Corporate catering leads',
      platform: 'LinkedIn',
      audience: 'Office managers & EA’s — Cape Town CBD',
      offer: 'Premium sushi & lunch platters for teams of 10–200',
      headline: 'Impress the boardroom at lunch',
      cta: 'Get a Quote',
      visualStyle: 'Corporate',
      colourDirection: 'charcoal gold food photography',
      notes: 'Sushi platter + corporate lunch scene',
      version: 1,
      status: 'Approved',
      imagePrompt: '# LinkedIn — Cutting Edge\nPremium sushi platter, corporate boardroom lunch, modern food branding.',
      visualDirection: 'Corporate catering · sushi hero · gold accents',
      feedbackNotes: 'Campaign Ready — launch Google Ads local.',
      approvalHistory: [
        { id: 'demo-h-c1', status: 'Approved', note: 'Campaign Ready', createdAt: T3 },
      ],
      actionId: 'demo-act-cuisine-creative',
    }),
    creative({
      id: 'demo-cr-cuisine-2',
      clientId: DEMO_CLIENT_IDS.cuisine,
      clientName: 'CUTTING EDGE CUISINE',
      productName: 'Cutting Edge Corporate Catering',
      campaignGoal: 'Event catering',
      platform: 'Facebook',
      audience: 'Event planners Cape Town',
      offer: 'Same-week event catering — sushi & canapés',
      headline: 'Cape Town events, catered flawlessly',
      cta: 'View Menus',
      visualStyle: 'Bold',
      colourDirection: 'warm orange red modern food',
      notes: 'Event spread wide shot',
      version: 2,
      status: 'Awaiting Approval',
      imagePrompt: '# Facebook — Cutting Edge\nEvent catering spread, sushi towers, warm lighting.',
      visualDirection: 'Event catering · bold warm palette',
      feedbackNotes: '',
      approvalHistory: [{ id: 'demo-h-c2', status: 'Awaiting Approval', note: 'V2', createdAt: T2 }],
    }),
    creative({
      id: 'demo-cr-cuisine-3',
      clientId: DEMO_CLIENT_IDS.cuisine,
      clientName: 'CUTTING EDGE CUISINE',
      productName: 'Cutting Edge Corporate Catering',
      campaignGoal: 'Office lunch subscription',
      platform: 'Instagram',
      audience: 'Tech & finance offices — Sea Point to Century City',
      offer: 'Weekly office lunch program — chef-designed menus',
      headline: 'Office lunch, elevated',
      cta: 'Book a Tasting',
      visualStyle: 'Minimal',
      colourDirection: 'white marble fresh greens',
      notes: 'Instagram story — office lunch',
      version: 3,
      status: 'Scheduled',
      imagePrompt: '# Instagram Story — Cutting Edge\nOffice lunch boxes, fresh sushi, minimal branding.',
      visualDirection: 'Minimal food brand · story safe zone',
      feedbackNotes: 'Scheduled for next week publish.',
      approvalHistory: [{ id: 'demo-h-c3', status: 'Scheduled', note: 'Publish Monday 09:00', createdAt: T3 }],
    }),
  ]

  const marketingMaterials = [
    {
      id: 'demo-mm-1',
      title: 'VYRON — Google RSA Headlines Pack',
      platform: 'Google Ads',
      materialType: 'google_headlines' as const,
      content: '1. Workforce Software South Africa\n2. Stop Payroll Leakage Today\n3. AI Clocking + Rostering Demo',
      productName: 'VYRON CORE',
      targetArea: 'South Africa',
      createdAt: T2,
    },
    {
      id: 'demo-mm-2',
      title: 'Bridgewater — Instagram Caption Set',
      platform: 'Instagram',
      materialType: 'instagram_post' as const,
      content: 'Wind down without the noise. Bridgewater Botanicals — crafted for evenings that matter. #SoberCurious #CapeTown',
      productName: 'Bridgewater Botanical Tonics',
      targetArea: 'Cape Town + Johannesburg',
      createdAt: T2,
    },
    {
      id: 'demo-mm-3',
      title: 'Cutting Edge — WhatsApp Corporate Outreach',
      platform: 'WhatsApp',
      materialType: 'whatsapp' as const,
      content: 'Hi {{name}} — Cutting Edge Cuisine delivers premium sushi & lunch catering for Cape Town offices (10–200 pax). Can we send this week’s menu?',
      productName: 'Cutting Edge Corporate Catering',
      targetArea: 'Cape Town',
      createdAt: T2,
    },
  ]

  const advertConcepts = creatives.slice(0, 3).map((c, i) => ({
    id: `demo-adv-${i}`,
    productName: c.productName,
    targetAudience: c.audience,
    platform: c.platform as 'Facebook',
    offerMessage: c.offer,
    style: 'Premium SaaS' as const,
    prompt: c.imagePrompt,
    createdAt: T2,
  }))

  const actionQueue: VyronActionQueueItem[] = [
    {
      id: 'demo-act-vyron-seo',
      title: 'Rank for workforce management software South Africa',
      subtitle: 'VYRON CORE — SEO War Room priority',
      priority: 'Critical',
      department: 'SEO War Room',
      sourcePage: 'SEO War Room',
      due: 'This week',
      status: 'ready_to_execute',
      createdAt: T,
      executionBrief: 'Close competitor gap on payroll-ready clocking. Ship comparison section + internal links from buyer guide.',
      nextSteps: ['Publish FAQ block', 'Add schema to landing page', 'Build 3 supporting blogs'],
      outputNeeded: 'SEO plan + content brief in queue output',
      generatedOutput: '## SEO Plan — VYRON CORE\n- Target URL: /workforce-management\n- Priority: workforce management software South Africa (vol 1.2k, difficulty 28)\n- Gap: Competitor weak on payroll-ready messaging\n- Forecast: Top 10 in 4–6 months with 6 blog cluster',
      kind: 'seo',
      contextMeta: {
        keyword: 'workforce management software South Africa',
        business: 'VYRON CORE',
        targetArea: 'South Africa',
        searchIntent: 'Buyer Intent',
        difficulty: '28',
        volume: '1200',
        suggestedDailyBudget: 'R500/day',
      },
    },
    {
      id: 'demo-act-vyron-ads',
      title: 'Launch Google Search test — VYRON CORE',
      subtitle: 'R500/day buyer intent — South Africa',
      priority: 'High',
      department: 'Google Ads AI',
      sourcePage: 'Google Ads AI',
      due: 'Today',
      status: 'in_progress',
      createdAt: T,
      executionBrief: 'Use saved plan demo-plan-vyron. Exact match on buyer keywords. Launch panel has full assets.',
      nextSteps: ['Open Launch Google Ads Setup', 'Copy keywords & RSA', 'Mark launched when live'],
      outputNeeded: 'Live Google Ads campaign with negatives',
      generatedOutput: googleAdsPlans[0].planText.slice(0, 500) + '…',
      kind: 'google_ads',
      contextMeta: {
        keyword: 'workforce management software South Africa',
        business: 'VYRON CORE',
        targetArea: 'South Africa',
        searchIntent: 'Buyer Intent',
        difficulty: '28',
        volume: '1200',
        suggestedDailyBudget: 'R500/day',
      },
    },
    {
      id: 'demo-act-vyron-creative',
      title: 'Approve Facebook creative — VYRON CORE',
      subtitle: 'Version 1 approved — launch campaign',
      priority: 'High',
      department: 'AI Creative Studio',
      sourcePage: 'AI Creative Studio',
      due: 'Today',
      status: 'ready_to_execute',
      createdAt: T2,
      executionBrief: 'Creative demo-cr-vyron-1 approved. Launch Google Ads Setup with attached headline & offer.',
      nextSteps: ['Launch Campaign Setup', 'Sync RSA headlines', 'Track demo conversions'],
      outputNeeded: 'Launched campaign + creative linked',
      kind: 'advert_image',
      advertMeta: {
        prompt: creatives[0].imagePrompt,
        platform: 'Facebook',
        audience: creatives[0].audience,
        style: 'Premium SaaS',
        productName: 'VYRON CORE',
        offerMessage: creatives[0].offer,
      },
      imageCreated: true,
    },
    {
      id: 'demo-act-bridge-content',
      title: 'Publish sober social blog — Bridgewater',
      subtitle: 'Content Engine — brand story',
      priority: 'Medium',
      department: 'Content Engine',
      sourcePage: 'Content Engine',
      due: 'Friday',
      status: 'pending',
      createdAt: T,
      executionBrief: 'Draft lifestyle blog targeting “sober alternative drink” with premium botanical positioning.',
      nextSteps: ['Open Content Engine', 'Generate marketing material', 'Queue Meta creative'],
      outputNeeded: 'Published blog + social snippets',
      kind: 'content',
    },
    {
      id: 'demo-act-bridge-ads',
      title: 'Build Display awareness — Bridgewater',
      subtitle: 'Cape Town + Johannesburg — R267/day',
      priority: 'Medium',
      department: 'Google Ads AI',
      sourcePage: 'Google Ads AI',
      due: 'Next week',
      status: 'pending',
      createdAt: T,
      executionBrief: 'Awareness campaign for premium non alcoholic beverage keywords. Pair with approved Instagram creative.',
      nextSteps: ['Generate campaign', 'Approve Instagram V1', 'Launch setup panel'],
      outputNeeded: 'Display + remarketing plan',
      kind: 'google_ads',
    },
    {
      id: 'demo-act-cuisine-seo',
      title: 'Local SEO — corporate catering Cape Town',
      subtitle: 'CUTTING EDGE — map pack push',
      priority: 'High',
      department: 'SEO War Room',
      sourcePage: 'SEO War Room',
      due: 'This week',
      status: 'in_progress',
      createdAt: T,
      executionBrief: 'Optimize Google Business Profile, landing page, and reviews workflow for corporate catering Cape Town.',
      nextSteps: ['GBP photos upload', 'Service page H1 match', '3 local citations'],
      outputNeeded: 'Top 3 map pack within 90 days',
      generatedOutput: '## Local SEO — Cutting Edge\n- Primary KW: corporate catering Cape Town\n- Gap: Weak competitor sushi corporate pages\n- Actions: GBP, menu schema, case study',
      kind: 'seo',
      contextMeta: {
        keyword: 'corporate catering Cape Town',
        business: 'CUTTING EDGE CUISINE',
        targetArea: 'Cape Town',
        searchIntent: 'Local',
        difficulty: '25',
        volume: '700',
        suggestedDailyBudget: 'R400/day',
      },
    },
    {
      id: 'demo-act-cuisine-creative',
      title: 'Launch LinkedIn creative — Cutting Edge',
      subtitle: 'Approved — Campaign Ready',
      priority: 'Critical',
      department: 'AI Creative Studio',
      sourcePage: 'AI Creative Studio',
      due: 'Today',
      status: 'ready_to_execute',
      createdAt: T2,
      executionBrief: 'Approved LinkedIn sponsored creative. Launch Google Ads local search with attached assets.',
      nextSteps: ['Launch Google Ads Setup', 'Copy headlines', 'Mark complete'],
      outputNeeded: 'Live search campaign + creative',
      kind: 'advert_image',
      advertMeta: {
        prompt: creatives[6].imagePrompt,
        platform: 'LinkedIn',
        audience: creatives[6].audience,
        style: 'Corporate',
        productName: 'CUTTING EDGE CUISINE',
        offerMessage: creatives[6].offer,
      },
      imageCreated: true,
    },
    {
      id: 'demo-act-cuisine-ads',
      title: 'Google Search — corporate catering Cape Town',
      subtitle: 'R400/day — high intent local',
      priority: 'High',
      department: 'Google Ads AI',
      sourcePage: 'Google Ads AI',
      due: 'Today',
      status: 'completed',
      createdAt: T,
      completedAt: T3,
      executionBrief: 'Campaign launched via Google Ads setup panel. Monitor search terms every 48h.',
      nextSteps: ['Review search terms', 'Pause waste keywords', 'Monthly report'],
      outputNeeded: 'Completed launch checklist',
      generatedOutput: googleAdsPlans[2].planText.slice(0, 400) + '…',
      kind: 'google_ads',
    },
    {
      id: 'demo-act-report',
      title: 'May agency report — all 3 clients',
      subtitle: 'Reports — rankings, spend, next actions',
      priority: 'Medium',
      department: 'Reports',
      sourcePage: 'Reports',
      due: 'Month end',
      status: 'completed',
      createdAt: T,
      completedAt: T3,
      executionBrief: 'Consolidated report for VYRON CORE, Bridgewater, Cutting Edge.',
      nextSteps: ['Share with clients', 'Queue June actions'],
      outputNeeded: 'PDF-ready report body',
      generatedOutput: '## May Marketing Report\n\n### VYRON CORE\n- Rankings: workforce management KW improved 4 positions\n- Ads: R500/day test — 12 demo requests\n\n### Bridgewater\n- Awareness up 18% — approve Instagram V1\n\n### Cutting Edge\n- Map pack #2 corporate catering Cape Town\n- Launched Google Search R400/day',
      kind: 'general',
    },
  ]

  const reports = [
    {
      id: 'demo-report-1',
      title: 'May 2025 — Agency Performance (3 Clients)',
      type: 'Monthly',
      period: 'May 2025',
      status: 'Ready' as const,
      body: [
        '# VYRON REACH — May Agency Report',
        '',
        '## VYRON CORE (Workforce SaaS)',
        '- **Rankings:** workforce management software SA ↑4 positions (now #14)',
        '- **SEO opportunity:** Payroll-ready clocking cluster — ship 2 blogs',
        '- **Ads:** R500/day Search — 12 demo requests, CPA R186',
        '- **Creatives:** Facebook V1 **Approved** — Campaign Ready',
        '- **Next:** Launch Google Ads setup panel checklist; scale +20% if CPA holds',
        '',
        '## BRIDGEWATER BOTANICALS',
        '- **Rankings:** sober alternative drink — top 20 entered',
        '- **Content:** Brand story blog ready for publish',
        '- **Ads:** R267/day display test queued — await Instagram approval',
        '- **Creative:** Instagram V1 approved; WhatsApp V3 declined — revise CTA',
        '',
        '## CUTTING EDGE CUISINE',
        '- **Local SEO:** corporate catering Cape Town — map pack #2',
        '- **Ads:** R400/day Search **launched** — 8 quote requests',
        '- **Creative:** LinkedIn corporate lunch **Approved** — Campaign Ready',
        '- **Next:** Office lunch subscription Instagram scheduled Monday',
      ].join('\n'),
      createdAt: T3,
    },
    {
      id: 'demo-report-2',
      title: 'VYRON CORE — SEO Opportunity Brief',
      type: 'SEO',
      period: 'Q2 2025',
      status: 'Ready' as const,
      body: 'Priority gap: payroll ready clocking system — competitor pages lack payroll integration proof. Recommend comparison table + calculator CTA.',
      createdAt: T2,
    },
  ]

  return {
    settings,
    clients,
    keywords,
    rankings,
    competitors,
    contentTasks,
    campaigns,
    actionQueue,
    reports,
    advertConcepts,
    googleAdsPlans,
    marketingMaterials,
    creatives,
    uploadedCreatives: [],
  }
}
